### ISSUE TITLE
android client does not work

### ISSUE THREAD

**Issue by betov69** [marienfressinaud/FreshRSS#3852]
I requested your support since android client not lets me connect to my FreshRSS server. I have already carried out all the necessary steps to connect (I am allowed to the API to connect and I have generated a password for the connection
)but it always sends the message "this URL is not correct" I attach screenshots of the problem for further reference, many thanks and greetings

**Docker versión 20.10.5
FreshRSS versión 1.18.1
FreshRSS client for F-Droid versión 1.3.6**

_note: I only use the service on my local network_

![Screenshot_20210916-160557__01](https://user-images.githubusercontent.com/90874504/133695196-27233802-c563-4db4-a048-78602dfe443f.jpg)
![RSSissue01](https://user-images.githubusercontent.com/90874504/133695232-a274b125-05d5-476c-9f63-c63e5c6b7b0b.png)
![RSSissue02](https://user-images.githubusercontent.com/90874504/133695235-0ae2eca1-b856-4c69-a6a1-12e9854de720.png)
![RSSissue03](https://user-images.githubusercontent.com/90874504/133695243-dc2aa6a5-430d-4b80-9faf-808c26c52513.png)

**Comment by math-GH** [comment]
Have you already asked the FreshRSS Android client project?

It has a own issue tracker: https://git.feneas.org/christophehenry/freshrss-android

**Comment by Alkarex** [comment]
Hello,
Something else, an address of the form `192.168.x.x` will only work on your local network.

**Comment by betov69** [comment]
> Have you already asked the FreshRSS Android client project?
> 
> It has a own issue tracker: https://git.feneas.org/christophehenry/freshrss-android

Thank you very much, I will review the case with them, best regards.
