### ISSUE TITLE
[BUG] Cron not updating (using docker-compose)

### ISSUE THREAD

**Issue by MightyCreak** [marienfressinaud/FreshRSS#3855]
**Describe the bug**
I've set up an instance using docker-compose, imported my feeds from tt-rss and it worked when I imported, but since then it seems like they aren't updated anymore.

**To Reproduce**
1. Run a service using docker-compose, changed only 4 things in the docker-compose.yml:
    - Changed DB port to `"8500:80"`
    - Generated the DB password
    - Changed `TZ` env var to `America/New_York`
    - Changed `CRON_MIN` env var to `'*/10'`
2. Import an OPML (might not be necessary, but some URLs are dead in it)
3. See that it imports everything
4. Wait for a new article to be published and long enough for cron to be fired up
5. See that the new article never appears in the list

**Expected behavior**
Update every 10 minutes and the new articles should appear (at least when refreshing the FreshRSS page)

**Environment information (please complete the following information):**
 - Device: Desktop
 - OS: Fedora 34
 - Browser: Firefox 92
 - FreshRSS version: 1.18.1
 - Database version: Postgresql (docker image `postgres:12-alpine`)
 - PHP version: the one in the docker-compose.yml OS
 - Installation type: docker-compose

**Additional context**
I'm new to FreshRSS, maybe there's something I missed somehow? Also I don't know how to verify that cron did indeed fire up.

**Comment by MightyCreak** [comment]
I've manually executed the cron command line in the freshrss-app container, and got this:
```
# . /var/www/FreshRSS/Docker/env.txt; su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'
FreshRSS[118]: SimplePie GET https://github.com/FreshRSS/FreshRSS/releases.atom
FreshRSS[118]: SimplePie GET https://tuxphones.com/rss/
FreshRSS[118]: SimplePie GET https://blog.funkwhale.audio/@/funkwhale/atom.xml
FreshRSS[118]: [creak] [Wed, 22 Sep 2021 15:42:14 -0400] [warning] --- cURL error 22: The requested URL returned error: 404  [https://blog.funkwhale.audio/@/funkwhale/atom.xml]
FreshRSS[118]: SimplePie GET https://www.demaindemaitre.ca/feed/
FreshRSS[118]: SimplePie MD5 cache match for https://www.demaindemaitre.ca/feed/
FreshRSS[118]: SimplePie GET https://f-droid.org/fr/feed.xml
FreshRSS[118]: SimplePie MD5 cache match for https://f-droid.org/fr/feed.xml
FreshRSS[118]: SimplePie GET http://www.penofchaos.com/naheulbeukrss.xml
FreshRSS[118]: SimplePie MD5 cache match for http://www.penofchaos.com/naheulbeukrss.xml
FreshRSS[118]: SimplePie GET https://www.phoronix.com/rss.php
FreshRSS[118]: SimplePie MD5 cache no match for https://www.phoronix.com/rss.php
FreshRSS[118]: SimplePie GET https://thisweek.gnome.org/index.xml
FreshRSS[118]: SimplePie MD5 cache match for https://thisweek.gnome.org/index.xml
FreshRSS[118]: SimplePie GET https://www.lespetitspasdenthalpie.com/feed.xml
FreshRSS[118]: [creak] [Wed, 22 Sep 2021 15:42:25 -0400] [warning] --- cURL error 22: The requested URL returned error: 404  [https://www.lespetitspasdenthalpie.com/feed.xml]
FreshRSS[118]: SimplePie GET https://bitwarden.com/blog/feed.xml
FreshRSS[118]: SimplePie MD5 cache match for https://bitwarden.com/blog/feed.xml
FreshRSS[118]: SimplePie GET https://fedoramagazine.org/feed/
FreshRSS[118]: SimplePie GET https://facil.qc.ca/commbref/feed
FreshRSS[118]: SimplePie MD5 cache match for https://facil.qc.ca/commbref/feed
FreshRSS[118]: SimplePie GET http://blog.system76.com/rss
FreshRSS[118]: SimplePie GET https://blog.system76.com/rss#_=_
FreshRSS[118]: SimplePie MD5 cache match for http://blog.system76.com/rss
FreshRSS[118]: SimplePie GET https://www.stresshumain.ca/feed/
FreshRSS[118]: SimplePie MD5 cache match for https://www.stresshumain.ca/feed/
FreshRSS[118]: SimplePie GET https://mesamatrix.net/rss.php
FreshRSS[118]: SimplePie MD5 cache match for https://mesamatrix.net/rss.php
FreshRSS[118]: SimplePie GET https://planet.gnome.org/atom.xml
FreshRSS[118]: SimplePie MD5 cache match for https://planet.gnome.org/atom.xml
FreshRSS[118]: SimplePie GET https://blog.coinbase.com/feed
FreshRSS[118]: SimplePie MD5 cache match for https://blog.coinbase.com/feed
FreshRSS[118]: SimplePie GET https://lepharmachien.com/feed/
FreshRSS[118]: SimplePie GET https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/series/new-york-times-privacy-project/rss.xml
FreshRSS[118]: SimplePie MD5 cache match for https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/series/new-york-times-privacy-project/rss.xml
FreshRSS[118]: SimplePie GET https://futurism.com/feed
FreshRSS[118]: SimplePie MD5 cache no match for https://futurism.com/feed
FreshRSS[118]: SimplePie GET https://ramblingblueowl.com/fr/feed/
FreshRSS[118]: SimplePie MD5 cache no match for https://ramblingblueowl.com/fr/feed/
FreshRSS[118]: SimplePie GET https://freshrss.org/feeds/all.atom.xml
FreshRSS[118]: SimplePie GET https://github.com/FreshRSS/FreshRSS/releases.atom
FreshRSS[118]: SimplePie GET https://matrix.org/blog/feed/
FreshRSS[118]: SimplePie GET https://matrix.org/blog/feed
FreshRSS[118]: SimplePie GET https://www.boredpanda.com/feed/
FreshRSS[118]: SimplePie MD5 cache no match for https://www.boredpanda.com/feed/
FreshRSS[118]: SimplePie GET https://www.inpact-hardware.com/rss-complet/239573/xxxxxxx
FreshRSS[118]: SimplePie MD5 cache match for https://www.inpact-hardware.com/rss-complet/239573/xxxxxxx
FreshRSS[118]: SimplePie GET http://www.joueurdugrenier.fr/feed/
FreshRSS[118]: [creak] [Wed, 22 Sep 2021 15:42:36 -0400] [warning] --- cURL error 6: Could not resolve host: www.joueurdugrenier.fr [http://www.joueurdugrenier.fr/feed/]
FreshRSS[118]: SimplePie GET http://blog.dota2.com/feed/
FreshRSS[118]: SimplePie GET https://www.dota2.com/blog_redirect/feed/
FreshRSS[118]: SimplePie GET https://www.dota2.com/news
PHP Notice: A feed could not be found at `http://blog.dota2.com/feed/`; the status code is `200` and content-type is `text/html; charset=UTF-8` in /var/www/FreshRSS/lib/SimplePie/SimplePie.php on line 1807
FreshRSS[118]: [creak] [Wed, 22 Sep 2021 15:42:37 -0400] [warning] --- A feed could not be found at `http://blog.dota2.com/feed/`; the status code is `200` and content-type is `text/html; charset=UTF-8` [http://blog.dota2.com/feed/]
FreshRSS[118]: SimplePie GET https://element.io/blog/rss/
FreshRSS[118]: SimplePie MD5 cache match for https://element.io/blog/rss/
FreshRSS[118]: SimplePie GET https://framablog.org/feed/
FreshRSS[118]: SimplePie GET https://www.nextinpact.com/rss-complet/239573/xxxxxxx
FreshRSS[118]: SimplePie MD5 cache match for https://www.nextinpact.com/rss-complet/239573/xxxxxxx
FreshRSS[118]: SimplePie GET https://godotengine.org/rss.xml
FreshRSS[118]: SimplePie GET https://nextcloud.com/blog/feed/
FreshRSS[118]: SimplePie GET https://nextcloud.com/blog/static-feed
FreshRSS[118]: SimplePie GET https://nextcloud.com/blog/static-feed/
FreshRSS[118]: SimplePie MD5 cache match for https://nextcloud.com/blog/feed/
Results: 
creak OK
End.
```

But now when I do it again I only get this (no matter how long I wait):
```
# . /var/www/FreshRSS/Docker/env.txt; su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'
Results: 
creak OK
End.
```

As if I was able to update once and now it doesn't try to fetch the feeds anymore.

**Comment by Frenzie** [comment]
Note that every 10 minutes won't happen, at least not for the same feed. That's purposefully rate limited. I'm on my phone atm so it may additionally be that the default is a bit higher still, see the settings.

**Comment by MightyCreak** [comment]
@Frenzie I'm browsing the documentation, but I can't see something related to a rate limit (except the `CRON_MIN` var :/ )

**Comment by Frenzie** [comment]
See Settings → Archiving.

Also see https://github.com/FreshRSS/FreshRSS/issues/2262#issuecomment-470060813
> We are part of an ecosystem. A typical reaction that we have seen from several servers is to simply ban by user-agent (that is why we had to remove "SimplePie" from our user-agent string, because it was too frequently banned), or to remove their RSS feed altogether. Bad user behaviours affect the larger community.
>
> If you need (near-)realtime updates, use the WebSub push mechanism, which is exactly meant for that, and is very easy to deploy server-side. FreshRSS has built-in client support for it.

**Comment by MightyCreak** [comment]
Gotcha! That was it. It was set to 1h (which is IMO way to long for my news) and I lowered it to 20 min.

I understand that we don't want to spam the feed's server, but I have two questions:
* Do you know how TinyTinyRSS does its feeds updates? (I didn't have issues and it felt like the updates were very short.. like 5 min, maybe less?)
* How can I enable WebSub? I don't know this tech. I've read the other thread, but it didn't really enlightened me ;)

**Comment by Frenzie** [comment]
Afaik they also have a rate limit of something like 15 or 20 minutes.

WebSub is for the publisher. These days it's fairly regularly enabled by default, and it's generally easy to enable on your own server. For example, see:

https://wordpress.com/support/pubsubhubbub/
https://wordpress.org/plugins/pubsubhubbub/

**Comment by Frenzie** [comment]
https://community.tt-rss.org/t/feed-update-interval-under-15-mins/2617/4
> The update daemon by default runs every two minutes, but of course it only updates feed that are due for an update, which is a minimum of 15 minutes. A cron job would be no different. The limit is coded into TT-RSS and if you want it to be different you’ll have to tweak some code.
>
> But please don’t be that person. Honestly, what possible reason is there for hitting a web site every 5 minutes or less? You’re creating unnecessary load on someone else’s server. If things are changing more frequently than the 15 minute interval allows, then contact the site’s admin and let them know so they can include more articles in their feed.

https://community.tt-rss.org/t/feed-update-interval-under-15-mins/2617/5
> Exactly this. RSS is NOT A REALTIME PROTOCOL! I’d ban your ip if you tried this with me.

**Comment by MightyCreak** [comment]
Good to know! Thank you for all these answers!

**Comment by dix** [comment]
@MightyCreak Sorry to dig-up this issue but while reading [your second post](https://github.com/FreshRSS/FreshRSS/issues/3855#issuecomment-925288585) with the logs I've seen that you forgot to remove your private key for the https://www.inpact-hardware.com/ & https://www.nextinpact.com/ _full_ feeds. 
I checked and they are still working. So basically you're offering everyone on the Internet your access to one of the perks of your subscription to NextINpact. 

I suggest you edit your post to remove the private key from the four (4) URL concerned and also generate a new private key so the people who already took advantage of this mistake won't be able to do so in the future.

To generate a new private key, once logged-in on NextINpact.com, click on your username at the top right of the screen, then _Compte_ tab and finally _Réinitialiser_ next to _Clé de sécurité_. 
When its done, you will have to update the feeds URLs in your FreshRSS interface.

Have a nice day

**Comment by aledeg** [comment]
@35am Thank you for reporting such thing. I've took the liberty to remove the keys from the message. But @MightyCreak, you need to update your keys ASAP.

**Comment by MightyCreak** [comment]
Oh dang! Thanks for telling me, I completely forgot they were private, I'll change them ASAP. Thank you!

Edit: I deleted the post history as well, so that they keys are no longer discoverable.
