### ISSUE TITLE
[Feature] Filter posts based on rules and not show them in the feed

### ISSUE THREAD

**Issue by the100rabh** [marienfressinaud/FreshRSS#3865]
**Is your feature request related to a problem? Please describe.**
Some of the feeds are overwhelming and with information, I am not interested in. If I could filter the posts based on certain rules, like words the title or hashtags in the post. 

**Describe the solution you'd like**
An extension which can do this for me

**Describe alternatives you've considered**
Currently ignoring and moving on is the only way forward.

**Additional context**
Happy to help code this up as an extension if I can get some guidance

**Comment by Alkarex** [comment]
Hello,
It is already possible to automatically mark as read new entries of a given feed:

![image](https://user-images.githubusercontent.com/1008324/135594358-42685bcd-50cf-4dc8-b8a0-389b829e36ca.png)


On our todo, it will be possible to do the same at category or global level.

**Comment by the100rabh** [comment]
Thanks, this is awesome. Pardon my ignorance.
