### ISSUE TITLE
[BUG] Docker container failed to start

### ISSUE THREAD

**Issue by kz0** [marienfressinaud/FreshRSS#3868]
**Describe the bug**
When using docker-compose to deploy a freshrss container it fails to start with the following error:

`?/bin/ash: syntax error: unexpected end of file (expecting ")")`
with latest-alpine

`</bin/bash: -c: line 1: syntax error: unexpected end of file`
with debian

**To Reproduce**
docker-compose.yml

```version: "3"

services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:latest-alpine
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/20
      - TZ=Europe/Paris
    networks:
      - services-net

volumes:
  freshrss-data:
    driver: "vsphere"
    driver_opts:
      Capacity: "50m"
      VolumeStore: "default"
  freshrss-extensions:
    driver: "vsphere"
    driver_opts:
      Capacity: "150m"
      VolumeStore: "default"

networks:
  services-net:
```

**Environment information (please complete the following information):**
 - Device: Vsphere Integrated Containers
 - OS: Photon OS
 - Installation type: Docker

**Comment by Alkarex** [comment]
Hello,
What about if you run the container manually?

```sh
sudo docker run --rm -p 8080:80 freshrss/freshrss:latest-alpine
```

**Comment by kz0** [comment]
Getting the same `/bin/ash: syntax error: unexpected end of file (expecting ")")` message. 
This error doesn't happen if i run a local docker daemon.

**Comment by Alkarex** [comment]
And are you able to run other non-FreshRSS images without problem?
What about `freshrss/freshrss` or `freshrss/freshrss:edge`?

**Comment by kz0** [comment]
I had no problems with other images so far portainer, watchtower, mongo and a few others.
Also I was using the `linuxserver/freshrss` image without any problems, but it's missing the mark as read if title option for the duplicates.
`freshrss/freshrss:edge` yeilds `</bin/bash: -c: line 2: syntax error: unexpected end of file` almost like `freshrss/freshrss`

Docker on Photon VCH must be doing some weird things that are causing this problem, it works fine in a local docker daemon.
Thank you for assistance, I'll try to build it and upload to a local repository in an attempt to see what's wrong and report back if i find anything.

Since this issue is out of scope, feel free to close this.

**Comment by kz0** [comment]
Just a quick update, i managed to identify the problem that causes the container not to start.
The command ` '/bin/bash' '-o' 'pipefail' '-c' '([ -z "$CRON_MIN" ] || cron) && . /etc/apache2/envvars && exec apache2 -D FOREGROUND' ` for some reason fails because of `pipefail`.
I've tried to change the quotes but so far i still couldn't get it to work.
