### ISSUE TITLE
[BUG] Subscription Management: reordering feeds

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#3892]
Subscription management:

Drag&Drop:
between categories (green marked): no problem
inside of a category (red): 404 error (cannot reorder)

![grafik](https://user-images.githubusercontent.com/1645099/137548514-76e1dc76-9866-4c2c-aeaa-bc91d04796cd.png)

**To Reproduce**
1. Go to subscription management
2. reorder a feed via drag and drop

**Expected behavior**
can reorder the feed inside of a category

**Environment information (please complete the following information):**
 - FreshRSS version: [e.g. 1.18.1]

**Comment by Frenzie** [comment]
> Expected behavior
can reorder the feed inside of a category

It may or may not be desirable, but I don't think it's expected. Unless I'm mistaken, they're just alphabetical (or probably the much worse ASCIIbetical). The 404 in the console's a bit weird and ugly of course.

**Comment by math-GH** [comment]
Ok, good point. The drag&drop look and feel looks like that is possible to reorder.

**Comment by math-GH** [comment]
I am on it.

I will bring a little bugfix for a small bug that is on this page.

The rest of fixing this issue can be planned for 1.20
