### ISSUE TITLE
[Improvement] i18n: upgrade our translations. 18 languages available

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#3898]
Dear community,

FreshRSS user interface is translated into 18 languages. Not all languages are covered by active developers.

Available languages:
- [ ] CZ: Czech (some phrases need a translation EN -> CZ) 🇨🇿
- [x] DE: German (active supported. 99.6% is translated) 🇩🇪🇦🇹🇨🇭
- [x] EN: British English (active supported. 100% is translated) 🇬🇧
- [x] EN_US: USA English (active supported. 100% is translated) 🇺🇸
- [x] ES: Spanish (some phrases need a translation EN -> ES) 🇪🇸🇲🇽
- [x] FR: French (active supported. 100% is translated) 🇫🇷
- [ ] HE: Hebrew (some phrases need a translation EN -> HE) 🇮🇱
- [ ] IT: Italian (some phrases need a translation EN -> IT) 🇮🇹
- [x] JA: Japanese (99% translated. Some less phrases need a translation EN -> JA)
- [x] KO: Korean (some phrases need a translation EN -> KO) 🇰🇷🇰🇵
- [x] NL: Dutch (active supported. 99.6% is translated)🇳🇱
- [x] OC: Occitan (some phrases need a translation EN -> OC)🇫🇷🇮🇹
- [x] PL: Polish (some phrases need a translation EN -> PL)🇵🇱
- [x] PT_BR: Brazil Portuguese  (99.9% done; one single missing translation EN -> PT_BR) 🇧🇷
- [x] RU: Russian (some phrases need a translation EN -> RU) 🇷🇺
- [x] SK: Slovakian (some phrases need a translation EN -> SK) 🇸🇰
- [ ] TR: Turkish (some phrases need a translation EN -> TR) 🇹🇷
- [x] ZH_CN: Chinese (some phrases need a translation EN -> ZH_CN)🇨🇳

The language files are PHP files in this folder: https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n

Do you miss your favorite language? Feel free to add it to our supported languages.

Please send us a Pull Request or use the comments below to improve the translations.

(Hacktoberfest participants are welcome to help)

**Comment by natastro** [comment]
Happy to help with Spanish translations 😊

**Comment by math-GH** [comment]
@Alkarex : please add also the `Hacktoberfest` label. Thanks :)

**Comment by math-GH** [comment]
@Frenzie : Could you do the NL translation and fix the left not translated phrases?

**Comment by math-GH** [comment]
I like it how it works. Great community work! 💓

**Comment by math-GH** [comment]
Hey @mat-mo, could you support us with the Hebraic translations?

**Comment by math-GH** [comment]
Hey @marcomrc, maybe you will read this: Could you support us with some Italian translations?

**Comment by math-GH** [comment]
Hey @312k, could you support us with some little Japanese translations?
Just 7 phrases in 3 files are not yet translated

![grafik](https://user-images.githubusercontent.com/1645099/144743792-ce36f415-44a5-47fc-a80f-37819f7ec00c.png)

**Comment by math-GH** [comment]
Cześć @wolfpld, could you please help us with an update of the Polish language files?

**Comment by math-GH** [comment]
Hey @tiborepcek, could you support us again with the Slovakian translations?

**Comment by math-GH** [comment]
Hey @hckweb, please support us with some Turkish translations to improve FreshRSS.

**Comment by tiborepcek** [comment]
> Hey @tiborepcek, could you support us again with the Slovakian translations?

Done. PR sent.

**Comment by Alkarex** [comment]
Call for translation update for our upcoming FreshRSS version 1.20.0 https://github.com/FreshRSS/FreshRSS/discussions/4517#discussioncomment-3444960
