### ISSUE TITLE
Using Space as Keyboard shortcut for "Jump to next Article" suddenly triggers additional scrolling

### ISSUE THREAD

**Issue by rom-1** [marienfressinaud/FreshRSS#3946]
One of the latest commits seemed to have broken the keyboard shortcut "jump to next article" when using "Space" as the shortcut with Google Chrome.

On the latest stable version 1.18.1, jumping to the next article with "space" worked perfectly. After updating to "1.19.0-dev", FreshRSS jumps to the next article AND Google Chrome does some additional scrolling which is the default behaviour on any website when pressing the space key.

See discussion here: https://github.com/FreshRSS/FreshRSS/issues/3891#issuecomment-953184909_

**Comment by stysebae** [comment]
Hello rom-1,
I checked when this bug was introduced: this problem appears since `24c2c47d4ba5783625bba9385a1c144d791985d9` ([here](https://github.com/FreshRSS/FreshRSS/commit/24c2c47d4ba5783625bba9385a1c144d791985d9)). 

@Frenzie, what is the purpose of using `addEventListener`instead of `.onkeydown`? Would it be problematic to use `.onkeydown` again?

**Comment by Frenzie** [comment]
There's nothing inherently wrong with it but it's also usually probably not what you want. My only concern was as stated: people will copy it.

**Comment by Frenzie** [comment]
But wait, what about my commit broke exactly then? I don't see anything wrong.

**Comment by Frenzie** [comment]
Oh, you mean you want e.preventDefault? It's disturbing if onkeydown doesn't require that, another mark against it tbh.

**Comment by stysebae** [comment]
Hey @Frenzie, yes, `e.preventDefault` fixes the problem, thank you. :-)

**Comment by Alkarex** [comment]
> Oh, you mean you want e.preventDefault? It's disturbing if onkeydown doesn't require that, another mark against it tbh.

@Frenzie That aspect was controlled by `return true;` vs. `return false;`

**Comment by Frenzie** [comment]
Yeah, since I wrote that I remembered the main distinction is the propagation, i.e., the ability to attach multiple event handlers without jumping through hoops. :-)
