### ISSUE TITLE
[BUG] Atom Feed of https://www.home-assistant.io/blog/ shows up as empty

### ISSUE THREAD

**Issue by chemical1979** [marienfressinaud/FreshRSS#3948]
**Describe the bug**
If you add https://www.home-assistant.io/blog/ as a source, it is recognized, but shown as empty. Feed Validation Service has something to argue about, but in general it seems to be a valid Atom 1.0 feed. 
It works for Feedly though. 
I wasn't able to find anything obvious in the logs.

**To Reproduce**
1. Go to Subscription Management
2. Add https://www.home-assistant.io/blog/ as source feed
3. See that feed is empty

**Environment information (please complete the following information):**
- FreshRSS version: 1.18.1, I am running c785cdfb003d30124b27ff41c9c622e0d30cb9f0
- PHP version: 7.3.31-1-deb10u1
- Installation type: Self-Hosted on raspbian buster

**Comment by math-GH** [comment]
The validation link: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.home-assistant.io%2Fatom.xml

**Comment by math-GH** [comment]
cannot confirm.

Works fine for me
![grafik](https://user-images.githubusercontent.com/1645099/139541204-98bf167a-e07b-4467-b0f1-5f8cedf26273.png)

Checked it on 1.18.1 and on edge branch

**Comment by chemical1979** [comment]
That's pretty weird. If I manually update the "empty" feed, this shows up in the logs:

> 2021-10-30 20:28:49 A feed could not be found at `https://www.home-assistant.io/atom.xml`. Empty body. [https://www.home-assistant.io/blog/]

**Comment by math-GH** [comment]
maybe your raspbian blocks content?

**Comment by chemical1979** [comment]
I added the atom.xml file specifically via https://www.home-assistant.io/atom.xml as feed URL and now it works. I guess the issue was that I added /blog at the end of the URL?
Anyway, resolving issue. Thanks @mathContao.
