### ISSUE TITLE
[BUG] De-escaping of escaped HTML tags in Atom <content> 

### ISSUE THREAD

**Issue by cweiske** [marienfressinaud/FreshRSS#3951]
Feed https://feed.ctrl.blog/latest.atom has escaped HTML `<video>` tags in its content tag:

```
<content type="html">&lt;p&gt;We’ve had the HTML &lt;code&gt;&amp;lt;video&amp;gt;&lt;/code&gt; element for over a decade. Yet, everyone still defaults to embedding YouTube frames instead of hosting their own videos. The underlying problem is that the &lt;code&gt;&amp;lt;video&amp;gt;&lt;/code&gt; element isn’t suitable for embedding short video files on webpages.&lt;/p&gt; &lt;p&gt;&lt;a href="https://www.ctrl.blog/entry/html-responsive-video.html#src=feed"&gt;Read more …&lt;/a&gt;&lt;/p&gt;</content>
```

When unescaping that code once, we get:
```
<p>We’ve had the HTML <code>&lt;video&gt;</code> element for over a decade. Yet, everyone still defaults to embedding YouTube frames instead of hosting their own videos. The underlying problem is that the <code>&lt;video&gt;</code> element isn’t suitable for embedding short video files on webpages.</p> <p><a href="https://www.ctrl.blog/entry/html-responsive-video.html#src=feed">Read more …</a></p>
```

Still, FreshRSS 1.18.1 renders video tags:
![2021-10-31 freshrss summary html tags 2](https://user-images.githubusercontent.com/59036/139571001-3d2154fb-d60a-432f-a935-b83ee021e319.png)

The HTML code used in the browser has the `<code>` tag and the `<video>` tag:
```
<code><video controls="controls" preload="none"></video></code>
```

The `<video>` tag should not be rendered at all as tag, but as code.

**To Reproduce**
1. Add feed https://feed.ctrl.blog/latest.atom
2. Show feed entry "The HTML `<video>` element needs to go back on the drawing board"
3. See error

**Expected behavior**
The video tag is shown verbatim and not as rendered video tag.

**Environment information (please complete the following information):**
- OS: Debian unstable
- Browser: Firefox 93
- FreshRSS version: 1.18.1
- Database version: MariaDB 10.1.48-0+deb9u2
- PHP version: 7.2.34-24+0~20210826.64+debian9~1.gbp428dfa
- Installation type: Manual from git

**Comment by math-GH** [comment]
@cweiske Is it still reproduceable? I can not find an article in the feed with a video

**Comment by cweiske** [comment]
No, the problem is gone. It looks correct now. 
Test feed: http://tmp.cweiske.de/video.atom

FreshRSS version is  1.19.1 .

**Comment by math-GH** [comment]
> FreshRSS version is 1.19.1 .

With FreshRSS version 1.19.2, more bugs were fixed ;)
