### ISSUE TITLE
[BUG] irregularities with purging with some feeds

### ISSUE THREAD

**Issue by rezad1393** [marienfressinaud/FreshRSS#3954]
**Describe the bug**
I have set my default purge policy as such:

Maximum number of articles to keep    10
Maximum age of articles to keep   1 month
Never delete favorites yes
Never delete labels yes
Never delete unread articles yes
Minimum number of articles to keep per feed  5

I was looking at the stats page in freshrss.
I saw that a youtube feed had 171 entries.
that was weird because youtube feeds are 15 entries only in rss feed.
so I checked the feed as saw that it had the purge policy set as default.
I unselected that and saw that the non-default (or older default) setting for that feed is as such.

Maximum number of articles to keep  200  unchecked
Maximum age of articles to keep 3 months unchecked 

Never delete favorites yes
Never delete labels yes
Never delete unread articles no
Minimum number of articles to keep 50

so I thought maybe the default doesn't get applied to this feed so after setting the max number to 20 I clicked submit.
then used the purge button in archiving tab.
and that cleared the huge feed archive for that feed.

now my question is why that feed didn't follow the default purge policy that is set for it and all the other feeds.

**Comment by Alkarex** [comment]
No problem after all?

**Comment by rezad1393** [comment]
yes.
It was my bad.
wanted to delete this but didnt know how.
