### ISSUE TITLE
[Feature] Fetch older articles from feed

### ISSUE THREAD

**Issue by level0dev** [marienfressinaud/FreshRSS#3955]
When adding a new rss feed, FreshRSS fetches x amount of articles (I assume the amount is setup somewhere in the rss/atom link somewhere). I have some sites that serve a 100, some that serve 3. It would be awesome if we could fetch more articles than the prescribed by the rss/atom link.

This could be done by either manually imputing a value in advanced option when adding a feed, or through some option in feed settings later on.

I am not sure if this is even possible, as I know nothing about the rss/atom spec. I just discovered this option in Inoreader (as I am currently trying to find a perfect rss solution for myself and checking out bunch of services) and found that it really works for how I am using rss.

**Comment by Frenzie** [comment]
Normally that's not possible since Atom/RSS is about notifying you of new content, not about mirroring websites. Some generators might accept an argument like `?n=100` to indicate where to start.

I would suspect Inoreader simply keeps its own cache, similar to how I have years worth of content for many feeds on my FreshRSS instance, but it could potentially be interesting to mention specific examples.

**Comment by level0dev** [comment]
Is there a way to somehow add the argument right now to do some testing?

I am sure some of the feeds I am using on inoreader are cashed, but I do have some niche feeds there that wouldn't be cashed unless they run a lot of crawlers on everything. Tonight I'll try to make some unlisted test website with rss and see if  it works on that to confirm.

**Comment by Frenzie** [comment]
NB When I said like I very much meant like. I have a vague recollection of having seen something like that, but I might simply be confused with OPDS. I'm only actively aware of a few generators that allow you to specify your own limit (up to a maximum set by the admin, of course). That looks like, for example: `index.php?action=.xml;type=rss2;limit=50`. You can imagine one that'd also take something like n=50 (i.e., start at 50), p/page=2, and so on.

**Comment by Frenzie** [comment]
Though in case of that limit thing, the upper limit might be higher than the default limit.

**Comment by math-GH** [comment]
How do we want to proceed here? As I understand FreshRSS cannot do anything, so I would close this ticket

**Comment by Alkarex** [comment]
We cannot do much from FreshRSS site. The user must search for a possible parameter on the source server to provide more entries. Otherwise, if articles are still listed on an HTML page but without RSS feed, we now support Web scraping https://github.com/FreshRSS/FreshRSS/pull/4220
