### ISSUE TITLE
Using RSS Guard with FreshRSS

### ISSUE THREAD

**Issue by mikae1** [marienfressinaud/FreshRSS#3958]
I'm running the latest version of RSS Guard and FreshRSS. I wonder how I go about adding my FreshRSS installation to RSS Guard. 

- I've used "FreshRSS" as "Service" in "Edit account". 
- My installation is at https://subdomain.domain.tld/freshrss/ and I've used that as "URL" in "Edit account". 
- I've added my username and password under "Authentication" in "Edit account".
- Allow API access is ticked in FreshRSS authentication settings.

When I run "Test setup" in RSS Guard I get `Network error: 'content not found'`. Ideas?

**Comment by Frenzie** [comment]
Did you try `https://subdomain.domain.tld/freshrss/api` and `api/greader.php`? (See the profile page in settings.)

**Comment by mikae1** [comment]
> Did you try `https://subdomain.domain.tld/freshrss/api` and `api/greader.php`? (See the profile page in settings.)

`https://subdomain.domain.tld/freshrss/api` did not change the error message. `https://subdomain.domain.tld/freshrss/p/api/greader.php` changed error message to `Network error: 'authentication failed'`. "Authentication token" and "API password" are blank in FreshRSS.

**Comment by Frenzie** [comment]
That's the one you need to use then. Set up an API password and you should be ready to go. :-)

**Comment by math-GH** [comment]
@mikae1 
is it solved?

**Comment by mikae1** [comment]
> @mikae1 is it solved?

Yeah, sorry. It's solved!
