### ISSUE TITLE
[BUG] errors on page: delete my user account

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#3970]
**Describe the bug**
Error 1:
User: non-admin user
Page: Profil
Error: JavaScript error
How to reproduce: just load the page. Nothing to do

![grafik](https://user-images.githubusercontent.com/1645099/141013100-f979dfc8-695c-4930-965c-66d9950f34f6.png)

Error 2:
User: non-admin user
Page: Profil
Error: cannot delete my account

Sub error 2.1: with wrong password: no message, that the password is wrong
Sub error 2.2: with correct password: no message. just reloads the page.

**Environment information (please complete the following information):**
- Browser:  Firefox 93
- FreshRSS version: 1.19.0-dev (did not check 1.18.1)
- Installation type: web server (on XAMP Error 3 throws a 404 error page)

**Comment by math-GH** [comment]
@Alkarex Please reopen. Only Error 1 is fixed, error 2 is still open (it is not an JS error)

**Comment by math-GH** [comment]
Some more investigation to error 2 (environment: XAMP):

user "test3" deletes himself
![grafik](https://user-images.githubusercontent.com/1645099/146836620-a595f607-8ce0-4158-8d2e-5ac9655890aa.png)

gets the error
![grafik](https://user-images.githubusercontent.com/1645099/146836663-055f0e93-5fbc-41ff-a672-95de36726eb5.png)

user folder ./data/test3 is not deleted complete
![grafik](https://user-images.githubusercontent.com/1645099/146836706-abaee08d-9591-4ba7-9875-87a9dcf80da8.png)

user tries to login
![grafik](https://user-images.githubusercontent.com/1645099/146836943-f5abaac2-adb9-481b-a0c2-c55509993d3f.png)

**Comment by Alkarex** [comment]
@math-GH I have just tried and could not reproduce the bug. Could you try again?

**Comment by Alkarex** [comment]
Ping @math-GH

**Comment by math-GH** [comment]
Sub error 2.1: User deletes himself with a wrong password:

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/b277907a-61a1-4b34-b3f6-b930d1e97375)

(tested on FreshRSS 1.23.2-dev PHP8.0 SQLite)

**Comment by math-GH** [comment]
Sub error 2.2: User deletes himself with a correct password:

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/a5b25859-9097-40de-9299-504d05977104).

php_error_log:
```
[08-Apr-2024 16:50:07 Europe/Berlin] PHP Warning:  unlink(.../data\users\test3/db.sqlite): Resource temporarily unavailable in ...\lib\lib_rss.php on line 892
[08-Apr-2024 16:50:07 Europe/Berlin] PHP Warning:  rmdir(.../data\users\test3): Directory not empty in ...\lib\lib_rss.php on line 896
```

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6285

**Comment by math-GH** [comment]
It does not fix it :/ Same behavior as before
