### ISSUE TITLE
[BUG] Jumping to next article with shortcuts does not load more articles at the bottom

### ISSUE THREAD

**Issue by rom-1** [marienfressinaud/FreshRSS#3974]
**Describe the bug**
When jumping to the next post/article using a keyboard shortcut works only until "the end of the page" is reached, new articles are not loaded even when there are ones in queue. Pressing the keyboard shortcut in this state, FreshRSS jumps to the next feed, leaving unread articles in the previous one.

In the setttings I have enabled the option: "Load more articles at the bottom of the page"

**To Reproduce**
1. Have a feed with about 80 posts // with a lot of content. (I am using CSS selectors to load content of the article)
2. Press keyboard shortcut for "Open the next (unread) article"
3. Press keyboard shortcut several times, watch the scoll bar, it will scroll down until the bottom of the page.
4. When at the end of the scroll bar pressing the keyboard shortcut again will switch to the next feed. There are still about 30 unread articles in the feed menu, but no content is loaded at the bottom of the page.

If there are no additional feeds, the view will simply stop, and won't switch anywhere though there are additonal articles available. Simply by using the mouse wheel to scroll up a little bit, then scroll down a bit, suddenly loads additional articles at the bottom of the page.

**Expected behavior**
There should be content loaded at the bottom of the page when using the keyboard shortcut to scroll down.

**Screenshots**
Not applicable

**Environment information (please complete the following information):**
- Device: PC
- OS: Windows 10
- Browser: Chrome 95
- FreshRSS version: 1.19.0-dev
- Database version: not relevant
- PHP version: not relevant]
- Installation type: selfhosted? shared hoster?

**Additional context**
No context

**Comment by math-GH** [comment]
@rom-1 is it still an issue? 
You found this issue on 1.19.0-dev. Now we are on 1.20.0-dev and I cannot reproduce it.

**Comment by rom-1** [comment]
@math-GH Hey! Yes, this issue does still persist.

[See demonstration video here](https://user-images.githubusercontent.com/37835829/185823424-83c8c257-5ad8-4bee-8948-d76db28b205a.mp4). I have this feed from "heise online" which contains 128 articles. If I use the "ENTER" Button to jump to the next unread article, you can see how the scroll bar on the right reaches its bottom very soon but there should still be some additional content below. Instead, FreshRSS jumps to the next feed/category when pressing "Enter". This does not happen if I use my mouse wheel to scroll down. Using the mouse, addidiontal content is loaded on the fly.

This also happens to me with other feeds, not just the "heise online" one. Still, I give you my heise online feed settings as an example: 
**Feed URL:** https://www.heise.de/rss/heise-atom.xml
**Mark an Article as read:** 
intitle:'Anzeige:'
intitle:'heise+'
**CSS Selectors:** #meldung .article-content, #meldung p.a-article-header__lead, #meldung .article-image

I just updated to the newest dev before doing the test/video:

![2022-08-22_03h49_38](https://user-images.githubusercontent.com/37835829/185823405-bbedbe26-b464-4f0a-9bd6-131bae13fe82.png)

**Comment by aledeg** [comment]
I have similar issues. The problem arise when displayed articles have a long content (in my case, a lot of pictures from reddit).
As the content is really long, it does not trigger the loading since it's positional. I think we should add a rule to trigger the loading when reaching the 5th to last displayed article.
The precedence should go first on the positional rule then the article rule. This way, it will still be smooth with feeds with no content (hacker news)

**Comment by aledeg** [comment]
To reproduce this behavior, I suggest using a reddit feed with a lot of pictures (https://www.reddit.com/r/sewing/new/.rss) with the reddit extension (https://github.com/aledeg/xExtension-RedditImage).

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/4532

**Comment by aledeg** [comment]
That was quick :)
