### ISSUE TITLE
[Feature] Could you consider adding a switch to turn off highlighting for the theme?

### ISSUE THREAD

**Issue by i-iooi-i** [marienfressinaud/FreshRSS#3982]
![动画](https://user-images.githubusercontent.com/1827701/142018926-44578683-3524-43da-afdd-bde283d4ca02.gif)

The theme is really great!
But at night, frequent flickering will break the immersion of reading. Maybe you can add a switch in the theme interface to let users choose whether to turn it on or off.
Thank you for all this!

**Comment by math-GH** [comment]
Which theme do you use?

Have you tried to fix it with the extension CustomCSS https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS ?

**Comment by i-iooi-i** [comment]
> Which theme do you use?
> 
> Have you tried to fix it with the extension CustomCSS https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS ?

It seems that the dark theme will flicker when it is turned on by default. For example: "Dark" and "Alternative dark". I don't think this is a mistake. It seems to be designed for some purpose. It's just not suitable for everyone. This flicker will distract some attention. Sorry, I don't know how to customize CSS to solve this phenomenon.

**Comment by Frenzie** [comment]
Which version is this? That's not how it seems to behave for me.

**Comment by i-iooi-i** [comment]
> Which version is this? That's not how it seems to behave for me.

![动画](https://user-images.githubusercontent.com/1827701/142731264-57c56f3c-5763-4736-b73d-79c6424afa83.gif)

I installed it in Synology's docker. I used chrome to browse. Just now, in order to troubleshoot the problem, I closed all browser extensions. The problem still exists. I installed the latest version, here:
https://registry.hub.docker.com/r/freshrss/freshrss/

**Comment by i-iooi-i** [comment]
> Which version is this? That's not how it seems to behave for me.
![Snipaste_2021-11-20_23-12-27](https://user-images.githubusercontent.com/1827701/142731593-3df36a93-4f7a-443b-ad9c-c15051dc4a8d.png)
I use the iPhone 12 test. When I tap an article with my finger, it will also trigger different color changes. I think this phenomenon does exist, not a problem with a certain device.

**Comment by Frenzie** [comment]
I don't know what latest means. This is what I see in 1.18.1. Are you referring to a dev version?

[screen-recording.zip](https://github.com/FreshRSS/FreshRSS/files/7574880/screen-recording.zip)

**Comment by i-iooi-i** [comment]
> I don't know what latest means. This is what I see in 1.18.1. Are you referring to a dev version?
> 
> [screen-recording.zip](https://github.com/FreshRSS/FreshRSS/files/7574880/screen-recording.zip)
![Snipaste_2021-11-21_01-07-26](https://user-images.githubusercontent.com/1827701/142735114-fee66589-b989-409e-bfe9-6e927d57f910.png)

OK, it seems that our situation is the same. 😂That is, in dark mode, switching articles will have two colors: black and gray. In fact, my initial question was to ask if it is possible to keep the color uniform when switching articles, such as fixed black or fixed gray. Sorry, my English expression is very poor.🥲

**Comment by i-iooi-i** [comment]
> 我不知道最新是什么意思。这是我在 1.18.1 中看到的。你指的是开发版吗？
> 
> [录屏.zip](https://github.com/FreshRSS/FreshRSS/files/7574880/screen-recording.zip)



> 我不知道最新是什么意思。这是我在 1.18.1 中看到的。你指的是开发版吗？
> 
> [录屏.zip](https://github.com/FreshRSS/FreshRSS/files/7574880/screen-recording.zip)

In addition, this GIF is great. I recommend it to you. https://github.com/NickeManarin/ScreenToGif

**Comment by Frenzie** [comment]
But the hover effect you're showing is wrong.

> In addition, this GIF is great.

Thanks for the suggestion. I'd normally use Peek, but I was testing Wayland and Peek doesn't seem to work in it.

**Comment by i-iooi-i** [comment]
> But the hover effect you're showing is wrong.
> 
> > In addition, this GIF is great.
> 
> Thanks for the suggestion. I'd normally use Peek, but I was testing Wayland and Peek doesn't seem to work in it.
![动画](https://user-images.githubusercontent.com/1827701/142735703-cf26732d-05f3-4465-9f98-908d17e2404c.gif)
I don't seem to see much difference. Here I take a screenshot again, hoping to help you find the problem.

![Snipaste_2021-11-21_01-30-38](https://user-images.githubusercontent.com/1827701/142735770-0de0461e-abb0-4d5b-983a-1d9d459f95f6.png)

The latest version I mentioned just now refers to the version from docker.

**Comment by math-GH** [comment]
Could you please make a screenshot of the used version number from "about" or "update" page?

**Comment by i-iooi-i** [comment]
> Could you please make a screenshot of the used version number from "about" or "update" page?

Here:

![Snipaste_2021-11-21_19-31-26](https://user-images.githubusercontent.com/1827701/142760106-a7e89a85-6e99-4d3d-a285-261c7d8438cc.png)

**Comment by math-GH** [comment]
I cannot reproduce this issue with 1.18.1 theme Dark and Alternative Dark (Browser: Firefox)

**Comment by i-iooi-i** [comment]
> I cannot reproduce this issue with 1.18.1 theme Dark and Alternative Dark (Browser: Firefox)

I don't think it's a problem now😂. I just hope to have a pure dark theme, instead of switching between gray and dark as it is now. There will be some visual confusion. Thank you very much for your help😊😊😊.

**Comment by math-GH** [comment]
With CustomCSS you can modify it as you wish ;)

**Comment by i-iooi-i** [comment]
> With CustomCSS you can modify it as you wish ;)

OK, although I don't know much about CSS, I can study it 😎😎

**Comment by math-GH** [comment]
Install the CustomCSS extension

and insert this lines into the configuration of the extension:
```
.flux:hover {
    background: inherit;
}
```

It should fix what you need

// Edit: it should be valid for "Alternative Dark" theme

**Comment by i-iooi-i** [comment]
> Install the CustomCSS extension
> 
> and insert this lines into the configuration of the extension:
> 
> ```
> .flux:hover {
>     background: inherit;
> }
> ```
> 
> It should fix what you need

![动画](https://user-images.githubusercontent.com/1827701/142764993-95376733-cf96-4c86-acdd-5510d6332050.gif)

Unfortunately, I don't know if I made a mistake, or CSS can't be applied to the docker version. It doesn't seem to work

**Comment by akimolll** [comment]
![动画1](https://user-images.githubusercontent.com/1827701/142765168-21049096-0d3f-4ecb-b171-b834e4595012.gif)


> Install the CustomCSS extension
> 
> and insert this lines into the configuration of the extension:
> 
> ```
> .flux:hover {
>     background: inherit;
> }
> ```
> 
> It should fix what you need

**Comment by i-iooi-i** [comment]
> Install the CustomCSS extension
> 
> and insert this lines into the configuration of the extension:
> 
> ```
> .flux:hover {
>     background: inherit;
> }
> ```
> 
> It should fix what you need

![动画1](https://user-images.githubusercontent.com/1827701/142765223-32e38026-d4fe-45c3-83f6-3956477c7b0a.gif)

Cool, CSS works on another dark theme "dark by: Ad", although it seems that the title is wrong

**Comment by math-GH** [comment]
I improved the line.

Try these lines for the theme "Alternative Dark"

```
.flux:hover, 
.flux.current.active {
    background: inherit !important;
}
```

**Comment by i-iooi-i** [comment]
> I improved the line.
> 
> Try these lines for the theme "Alternative Dark"
> 
> ```
> .flux:hover, 
> .flux.current.active {
>     background: inherit !important;
> }
> ```

Great, it succeeded! I want to share this with my friend, who is also troubled by this problem. I really appreciate your help! 。❤️😍

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/4874
