### ISSUE TITLE
[BUG] "not" and "OR" operators don't work together on "Filter actions" → "Mark an article as read…"

### ISSUE THREAD

**Issue by ghost** [marienfressinaud/FreshRSS#3987]
**Describe the bug**
If you have two "not" filters (`-` or `!`) and add an `OR` operator between them, both filters appear to be ignored.

**To Reproduce**
1. Add a new feed
2. Use URL: https://www.austincityjobs.org/postings/all_jobs.atom
3. After adding the feed, scroll to 'Filter actions' → 'Mark an article as read…'
4. Add something like `!intitle:'IT Support Analyst' OR !intitle:'IT Systems Administrator'`
5. When the feed is refreshed/updated, articles with those titles are still marked as read (along with all other articles), when they **should not be**.

If you manually go to the feed's items and do a search like the above, it does indeed filter correctly and would only show you jobs not containing either of the criteria in the title.

Note: the behavior is the same whether you use `-` or `!` for `NOT`.

**Expected behavior**
The opposite of the above should happen. Articles meeting the criteria **should not be marked as read**.

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: N/A
- OS: Docker
- Browser: N/A
- FreshRSS version: Docker 1.18.1
- Database version: Docker, idk
- PHP version: Docker, 7.4.25
- Installation type: Docker (image: `lscr.io/linuxserver/freshrss:latest`)

**Additional context**
Feel free to test thing with any feed, I'm just using the above as an example as it's where I've seen the failure in the real world.

**Comment by math-GH** [comment]
Did you check #3915 and #3236 ?

Short: try `AND` instead of `OR`

(because of: https://en.wikipedia.org/wiki/De_Morgan%27s_laws)

**Comment by ghost** [comment]
I read https://github.com/FreshRSS/FreshRSS/issues/3236#issuecomment-891219460 and appreciate the detailed explanation, but I don't *get* it (that's on my, not the comment author). I'll try it out and closed the issue once verified to resolve for me.

**Comment by ghost** [comment]
What do you know, one came through and that seems to work!

Would y'all (@math-GH and other maintainers) be open to a PR for the documentation that mentions this logic "issue" (the issue is us normies trying to comprehend it and doing so incorrectly)? I could write something up quick (only in English, though) about it.

**Comment by math-GH** [comment]
It is not an issue. It is De Morgan's law.

The opposite of `A and B` is `not(A) or not (B)`

**Comment by ghost** [comment]
The fact that there's already been issues opened about this shows that it's not an immediately understood logic concept that some people are getting tripped up on.

If the project isn't interested in minor updates to documentation that would help alleviate wasted time on future GitHub issues being opened about it, then I won't bother.

Thanks for the assistance. 🙂

**Comment by Frenzie** [comment]
Of course documentation PRs are always welcome!

That being said, I'm having trouble reading your OP as anything other than "always", although I get what you intend to do. It's always not a or not b.

**Comment by ghost** [comment]
The logic that (I assume other non-programmers like myself) is being applied is:
> Articles that don't have 'abc' `OR` 'xyz' in the title should be marked read."

Putting `AND` makes it sound like:
> "Articles that don't have 'abc' *and* 'xyz' in the title should be marked read."

...which would be a drastically different situation than desired. Obviously, that's not what's actually happening, but it's a fairly reasonable logical conclusion from anyone not versed in programming logic, imo.

Hopefully that clears up where the users, including myself, are coming from.

**Comment by Frenzie** [comment]
High school physics, not programming logic (for me in the Netherlands). ;-)

Edit: and I note that @math-GH linked to algebra. It may have been both? In physics it was related to designing circuits.

**Comment by math-GH** [comment]
Negation of logic is not always simple.

**Comment by ghost** [comment]
Thanks again for the help @math-GH. Hopefully that PR is clear enough.

**Comment by Frenzie** [comment]
I guess my bizarre comment just means I'm getting old. To me programming is broadly speaking a more awkward way of writing and applying the stuff we learned in math and physics between roughly the ages of 12 and 14. For anybody born after '95 or so that might well be the reverse.

**Comment by ghost** [comment]
I suppose the confusion would be that I used "programming" as a verb. As in, the act of constantly putting to use knowledge (in this case: logic principles learned at some point during school) you gained previously so you actually retain it. 😅

I think I also mistook the comment, partially, as "hurr durr non-Euro education bad" which gets very old around other parts of the Internet. I realize that probably wasn't the intent.

**Comment by Frenzie** [comment]
For the record, American physics textbooks are highly regarded around the world as stellar examples.
