### ISSUE TITLE
FreeBSD installation problem

### ISSUE THREAD

**Issue by lpvm** [marienfressinaud/FreshRSS#3994]
I'm trying to install FreshRSS to a FreeBSD's jail.
The setup is done with a reverse proxy sending requests to a `lighttpd` web server with a `php-fpm` `fastcgi` system.

If I understood the instructions correctly, (_Put the application somewhere on your server (expose only the ./p/ folder to the Web_) the document root of the web server is pointing to `/usr/local/www/freshrss/p`.  Is this correct?
All the tree `/usr/local/www/freshrss` is owned by `www:www`, the user and group under which `lighttpd` and `php-fpm` are running.

When accessing `mydomain.com`, for one second there's the blue logo of freshrss, but then I get a 404 not found error.
In the browser bar, the url changes to `mydomain.com/p/i/`

I've placed a `info.php` at the `p/` directory and it is loaded and interpreted fine.
Do you have an idea of what is wrong?

FreshRSS is running the latest version.

**Comment by Alkarex** [comment]
Try to put your `info.php` into `/usr/local/www/freshrss/p/i/` and see whether that works.
If that works, please check your Web server logs, and FreshRSS logs.

**Comment by lpvm** [comment]
If the document root of the web server is pointing to the root of the FreshRSS (and not to the `p/` path), 
`https://freshrss.myhost.com/p/i/info.php` is interpreted.
Then, when accessing the `/p/i/` url path, the logs show an error:
```
2021-11-26 15:16:48: mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  Unknown: function &quot;1&quot; not found or invalid function name in Unknown on line 0
2021-11-26 15:16:48: mod_fastcgi.c.487) FastCGI-stderr:PHP Fatal error:  Uncaught Error: Call to undefined function filter_var() in /usr/local/www/freshrss/constants.php:33
2021-11-26 15:16:48: mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
2021-11-26 15:16:48: mod_fastcgi.c.487) FastCGI-stderr:#0 /usr/local/www/freshrss/p/i/index.php(23): require()
mod_fastcgi.c.487) FastCGI-stderr:#1 {main}
mod_fastcgi.c.487) FastCGI-stderr:  thrown in /usr/local/www/freshrss/constants.php on line 33
mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  Unknown: function &quot;1&quot; not found or invalid function name in Unknown on line 0
mod_fastcgi.c.487) FastCGI-stderr:PHP Fatal error:  Uncaught Error: Call to undefined function filter_var() in /usr/local/www/freshrss/constants.php:33
mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
mod_fastcgi.c.487) FastCGI-stderr:#0 /usr/local/www/freshrss/p/i/index.php(23): require()
mod_fastcgi.c.487) FastCGI-stderr:#1 {main}
mod_fastcgi.c.487) FastCGI-stderr:  thrown in /usr/local/www/freshrss/constants.php on line 33
mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  Unknown: function &quot;1&quot; not found or invalid function name in Unknown on line 0
mod_fastcgi.c.487) FastCGI-stderr:PHP Fatal error:  Uncaught Error: Call to undefined function filter_var() in /usr/local/www/freshrss/constants.php:33
mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
mod_fastcgi.c.487) FastCGI-stderr:#0 /usr/local/www/freshrss/p/i/index.php(23): require()
mod_fastcgi.c.487) FastCGI-stderr:#1 {main}
mod_fastcgi.c.487) FastCGI-stderr:  thrown in /usr/local/www/freshrss/constants.php on line 33
```

**Comment by Alkarex** [comment]
The public root should best be the `./p/` folder.
The errors are not due to that but visibly some missing PHP extensions.
Filter is supposed to be installed by default ( https://php.net/filter.installation ), but maybe that is not the case on your FreeBSD system:
Quick search: https://freebsd.pkgs.org/13/freebsd-amd64/php74-filter-7.4.21.txz.html

See the list of modules for Linux Debian:
https://github.com/FreshRSS/FreshRSS/blob/392861b7c3f9c6ff4588ad755a62514c6951e86a/Docker/Dockerfile#L11-L12

Or for Linux Alpine:
https://github.com/FreshRSS/FreshRSS/blob/392861b7c3f9c6ff4588ad755a62514c6951e86a/Docker/Dockerfile-Alpine#L7-L9

Alternatively, you can use one of our official Docker images:
https://hub.docker.com/r/freshrss/freshrss

**Comment by lpvm** [comment]
Hi, @Alkarex, thank you for your support.
Docker is not supported on FreeBSD.
Indeed, there were some php packages missing.

When accessing `https://freshrss.myhost.com/i/info.php`, which sits at `p/i/info.php` (document root set at `p/`) there's a line outputted to the webserver's error log:
`mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  Unknown: function &quot;1&quot; not found or invalid function name in Unknown on line 0`

How to enable the logs from FreshRSS?  Maybe I can find something useful there.

**Comment by lpvm** [comment]
After visiting `https://freshrss.myhost.com/i/` FreshRSS is working, but that doesn't happen if the URI visited is `https://freshrss.myhost.com`. 
Is this correct?

**Comment by Alkarex** [comment]
There is an automatic redirection, but maybe your lighthttpd config does not find index.html and only index.php.
If that is the case, we can add an index.php file as well

**Comment by lpvm** [comment]
I've placed a rewrite rule and the access is done from the base url now.
For someone with the same problem using lighttpd:
```
server.document-root = "/usr/local/www" + "/freshrss/p/"
url.rewrite-once            = ( "^/$"             => "./i" )
```
Thank you @Alkarex.  All the best!
