### ISSUE TITLE
Time for a V1.19.0 release?

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#4000]
Hi FreshRSS community,

what do you think: Is it time for a V1.19.0 release?

1.18.0 was released in March, 1.18.1 was released in June 2021.

It would be a nice "X-Mas present" ;)

**Comment by Alkarex** [comment]
Yes @math-GH 
We are already in the stabilisation phase before release https://github.com/FreshRSS/FreshRSS/milestone/48
I am in late updating the changelog https://github.com/FreshRSS/FreshRSS/blob/edge/CHANGELOG.md to make the call for testing announcement. Help welcome :-)
And there some small regressions such as https://github.com/FreshRSS/FreshRSS/pull/3986#issuecomment-978941494
I hope we can make the call for testing in the coming days and the actual release a few days later

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/4093
