### ISSUE TITLE
[BUG] Every feeds from bibliogram turn into unread.

### ISSUE THREAD

**Issue by OctopusET** [marienfressinaud/FreshRSS#4001]
**Describe the bug**
Every feeds from bibliogram rss feeds are turning to unread.

**To Reproduce**
1. Mark bibliogram feeds as read.
2. Reload after few times.
3. Every feeds are marked as unread.

**Expected behavior**
Never turn back to unread.

**Environment information**
- Device: Every device
- OS: Debian 11
- Browser: Every Browser
- FreshRSS version: 1.19.0-dev with latest git.
- Database version: MariaDB 15.1
- PHP version: PHP 8.0
- Installation type: local installation 

I'm using this instance.
https://bibliogram.pussthecat.org/

**Comment by math-GH** [comment]
strange.
I cannot reproduce it.

**Comment by OctopusET** [comment]
@math-GH Should I share my instance or config file?

**Comment by math-GH** [comment]
Could you share a feed link?

**Comment by OctopusET** [comment]
@math-GH I'm sorry but what feed? My freshrss instance rss feed or bibliogram's feed?

**Comment by math-GH** [comment]
A RSS feed from bibliogram, that you import into FreshRSS.

**Comment by OctopusET** [comment]
I have over 300 feeds from bibliogram.

Here's one of them.It also marks as unread after reload.
https://bibliogram.pussthecat.org/u/mozillagram/rss.xml


Should I share whole feeds list?

**Comment by Alkarex** [comment]
@OctopusET Please check which settings you have,

at global level:
![image](https://user-images.githubusercontent.com/1008324/144132800-10b9f8d8-7500-4fb0-b5e3-5fc20c3e3156.png)

and at feed level:
![image](https://user-images.githubusercontent.com/1008324/144132708-2bb418e8-b3d9-4f36-86f6-75833f6a2b82.png)

**Comment by OctopusET** [comment]
@Alkarex I didn't check off "Mark updated articles as unread". I should've checked configure page much more.

Wow this fixes everything. Thanks!
