### ISSUE TITLE
Transparent menus are a mess

### ISSUE THREAD

**Issue by triatic** [marienfressinaud/FreshRSS#4002]
The transparent menus in the latest edge build make things very difficult to read. The menu should be opaque. 

Without menu:

![Screenshot 2021-11-28 130530](https://user-images.githubusercontent.com/42704418/143769144-033b2615-91dc-4188-ace3-5e6334cca5d8.png)

With menu:

![Screenshot 2021-11-28 130545](https://user-images.githubusercontent.com/42704418/143769151-254fba5b-3b6d-4a2c-893a-d89d7470619e.png)

**Comment by Frenzie** [comment]
I can't confirm, assuming you mean 4cfeb96f3ded4e8cde1157d62b10d3051cd06bda.
![Screenshot_2021-11-28_15-37-40](https://user-images.githubusercontent.com/202757/143772478-5d30230d-1fb1-42fb-9d50-49e24fb8e2c5.png)

**Comment by triatic** [comment]
It seems the issue affects Chrome (Windows) but not Firefox (Windows).

**Comment by Frenzie** [comment]
It has some issues on Firefox too (e.g., the arrow triangle thing at the top is missing). I don't have time to investigate properly atm but https://github.com/FreshRSS/FreshRSS/pull/3881 sounds like it might be relevant taking a quick look at the commits.

**Comment by triatic** [comment]
The `<ul>` "scrollbar-thin" class has a transparent background. It appears Chrome is applying this background to the entire menu,

**Comment by math-GH** [comment]
can confirm. Will check it

**Comment by math-GH** [comment]
> It has some issues on Firefox too (e.g., the arrow triangle thing at the top is missing). I don't have time to investigate properly atm but #3881 sounds like it might be relevant taking a quick look at the commits.

Firefox (Windows):
It is there but it is not visible.
![grafik](https://user-images.githubusercontent.com/1645099/143787260-4b388d86-b2aa-4fb0-9600-7671ba819748.png)

![grafik](https://user-images.githubusercontent.com/1645099/143787268-739200d5-ce3d-4561-bed2-f7c8bf184b9d.png)

In Chromium (Windows) it works fine.
![grafik](https://user-images.githubusercontent.com/1645099/143787367-ca73d5a2-3700-4ec9-a82d-1e620aa5794c.png)

**Comment by math-GH** [comment]
This PR will fix the transparent menu.

How to fix the triangle thing in Firefox: I do not have still any clue how to fix it

**Comment by Frenzie** [comment]
@math-GH Did you add `overflow-y: auto` on `#sidebar, .scrollbar-thin`? Disabling that does the trick.

**Comment by Frenzie** [comment]
https://github.com/FreshRSS/FreshRSS/blob/4cfeb96f3ded4e8cde1157d62b10d3051cd06bda/p/themes/base-theme/template.css#L530

Edit: must be some other change interacting with that 3-year-old line. Anyway, that's one possible workaround. You'd have to try a few older commits see which change did it.

**Comment by math-GH** [comment]
can confirm, that deleting the overflow-y solves the issue.
I found the reason for this issue: with #3881 I added the CSS class `scrollbar-thin` to the config dropdown menu, that added the `overflow-y: auto`

I think #4005 will fix it and hopefully it will not destroy other things
