### ISSUE TITLE
Add PHPstan in project and CI

### ISSUE THREAD

**Issue by ColonelMoutarde** [marienfressinaud/FreshRSS#4016]
PHPstan is a very powerful tool that does static code analysis. It is highly recommended for this project. 

Attention, it is compatible only from php7. It is therefore an addition that must be made in the roadmap.

**Comment by Alkarex** [comment]
We are already at PHP7+, having dropped PHP5 recently :-)
Additional information and PRs welcome!

**Comment by math-GH** [comment]
@ColonelMoutarde : do you know how to set-up it? I have a look on PHPstan but did not tried it yet

**Comment by Frenzie** [comment]
```
docker run --rm -v $(pwd):/app ghcr.io/phpstan/phpstan analyse /app
```
[phpstan-output.txt](https://github.com/FreshRSS/FreshRSS/files/7644427/phpstan-output.txt)

**Comment by Alkarex** [comment]
We are now passing PHPStan level 0 and 1 https://github.com/FreshRSS/FreshRSS/pull/4021 and it is added to our continuous integration.
Help welcome to pass PHPStan level 2 https://github.com/FreshRSS/FreshRSS/issues/4103

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/pull/4110 for PHPStan level 3

**Comment by Alkarex** [comment]
Now up to level 5 https://github.com/FreshRSS/FreshRSS/pull/4110
