### ISSUE TITLE
[BUG] deprecation warnings with PHP 8.1

### ISSUE THREAD

**Issue by candrews** [marienfressinaud/FreshRSS#4017]
**Describe the bug**
Deprecation warnings are reported.

I'm using current `master`, commit 28cff8a0df3af23f7acf01840da43c098c779313 with PHP 8.1.0.
```
PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/localhost/htdocs/FreshRSS/app/Models/Feed.php on line 408
```

**To Reproduce**
Using PHP 8.1, run `actualize_script.php`

**Expected behavior**
No deprecation or other errors should be reported.

**Screenshots**
n/a

**Environment information (please complete the following information):**
- Device: Linux
- OS: Linux
- Browser: n/a
- FreshRSS version: current `master`, 28cff8a0df3af23f7acf01840da43c098c779313
- Database version: MariaDB 10.6.5
- PHP version: 8.1.0
- Installation type: self hosted

**Additional context**
I thought I had seen all the deprecation warnings in https://github.com/FreshRSS/FreshRSS/issues/4010 but I didn't notice this one as it only happens sometimes, I'm guessing only when new items appear in the feed.

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/4018

**Comment by candrews** [comment]
Confirmed, that seems to fix the problem :+1:

**Comment by Alkarex** [comment]
More PHP 8.1 issues can be caught with https://github.com/FreshRSS/FreshRSS/pull/4121
