### ISSUE TITLE
[BUG] Unknown error for feed [https://bytexd.com/feed/]

### ISSUE THREAD

**Issue by Quentin-ctrL** [marienfressinaud/FreshRSS#4022]
**Describe the bug**
Adding new feed : https://bytexd.com/feed/
The feed canno't be added
log : "Unknown error for feed [https://bytexd.com/feed/]"

**Environment information (please complete the following information):**
- OS: OVH shared hosting
- Browser: Firefox ESR
- FreshRSS version: 1.19.0-dev. 
- Database version:  sqlite
- PHP version:7.3.31
- Installation type: -

**Additional context**
The feed is valid according to 
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbytexd.com%2Ffeed%2F

**Comment by math-GH** [comment]
For me it was not an issue to add this feed. Can you reproduce this error?

Could you please look into your logs?

**Comment by Quentin-ctrL** [comment]
>  Le flux ne peut pas être ajouté. Consulter les logs de FreshRSS pour plus de détails. Vous pouvez essayer de forcer l’ajout par addition de #force_feed à l’URL.

```
2098 [Sun, 05 Dec 2021 16:26:04 +0100] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://bytexd.com/feed/]
2099 [Sun, 05 Dec 2021 16:26:16 +0100] [warning] --- Unknown error for feed [https://bytexd.com/feed/]
2100 [Sun, 05 Dec 2021 16:26:24 +0100] [warning] --- Unknown error for feed [https://bytexd.com/feed/]
```

**Comment by math-GH** [comment]
Can you add other feeds? (just to make sure, that you do not have any general issue with your connections)
This feed returns HTTP503 error (Service is temporarily Unavailable).
Maybe you have an issue with a proxy?

You can force the adding: just add `#force_feed` at the end of the feed url = `https://bytexd.com/feed/#force_feed`. It will add the feed into FreshRSS but it will not solve your connection issue.

**Comment by Quentin-ctrL** [comment]
Yes I can add new feeds.
I have only 2 feeds in error but no issue with the others.

using https://bytexd.com/feed/#force_feed > same error, the feed is not added in FreshRSS

It could be a server side issue, I need to test. 

I think you can close the issue if it's not related to FreshRSS

Thanks for your help ;)

**Comment by Alkarex** [comment]
Sometimes, feeds are blocked based on IP address, or user-agent. Try from your server:

```sh
curl -v 'https://bytexd.com/feed/'
```
