### ISSUE TITLE
[BUG] Feeds Not Showing Under Category 

### ISSUE THREAD

**Issue by BrodyStone21** [marienfressinaud/FreshRSS#4029]
I'm on Ubuntu 20.04 LTS. I'm running FreshRSS in Docker. I've got everything working fine, but some of my feeds are disappearing from their categories. After removing the feed and re-adding they reappeared but now, I've had a few more disappear. I'm running Maria DB as my database.

I've also experienced issues with the entire category disappearing from the home screen but I can still find everything well under Subscription Management. 

Any ideas?

![image](https://user-images.githubusercontent.com/36679309/144770010-bf0d8e21-28fa-403d-813c-db4ff949a103.png)
![image](https://user-images.githubusercontent.com/36679309/144770023-df029c88-5a3c-465c-b34c-8f6b24a4ab78.png)
![image](https://user-images.githubusercontent.com/36679309/144770039-9ab4b0ea-9d7f-4545-8c3a-b1a7fc1bab0f.png)

Is there any way that I could try to clear my cache? I tried using the purge function but wasn't having success. 

EDIT: Alright, apparently clicking the "update" button under the desired feed in subscription management resolved the issue. Is there a way to make feeds auto update?

EDIT 2: Sike, get pranked. It looks like the articles aren't being added to the main stream or showing the number of new articles. 

![image](https://user-images.githubusercontent.com/36679309/144770302-9e948610-74c0-4490-91cd-014d67ed3742.png)

Additionally, after I restarted the docker container these disappeared again.

**Comment by Frenzie** [comment]
The default view hides what you've previously read. You can change things in the settings or on the fly with the icons at the top of the stream.

**Comment by math-GH** [comment]
@BrodyStone21 : Is it solved for you?

**Comment by BrodyStone21** [comment]
>The default view hides what you've previously read. You can change things in the settings or on the fly with the icons at the top of the stream.

@Frenzie I was pulling 25 articles per source and definitely was not reading them, so that couldn't of been the issue. 

>@BrodyStone21 : Is it solved for you?

@math-GH well, I haven't had it happen since, but I also haven't made any changes lately. What I ended up doing to fix it originally was deleted everything and completely reinstalling.

**Comment by math-GH** [comment]
Is it possible to reproduce it?

**Comment by BrodyStone21** [comment]
Possibly, I'm not in front of my computer anymore but I'll try to intentionally break it again tomorrow and get back with you. 

Could you point me to whatever log files might contain relevant information?

**Comment by BrodyStone21** [comment]
I never got around to reproducing this, but I haven't had the issue since. Going to go ahead and close this.
