### ISSUE TITLE
Cannot connect from Android apps with fresh install - "This URL is not correct"

### ISSUE THREAD

**Issue by binarydad** [marienfressinaud/FreshRSS#4045]
**Describe the bug**
I have a fresh docker install of FRSS behind a nginx proxy to the port for the container, also handing SSL. I can access via the website perfectly fine. The `/api/` service check shows OK for both greader and fever. However, when trying to use the F-Droid FreshRSS app or any of the other readers that support FRSS, it says varying messages about the URL not being valid or can't authenticate. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1760607/145218827-02ec463e-2ead-4862-b5af-74fff6d7330b.png)

**Environment information (please complete the following information):**
- Device: Android Galaxy S8
- OS: Ubuntu 20 running latest docker/image
- FreshRSS version: 1.18.1
- Database version: MariaDB 10.6
- PHP version: docker version
- Installation type: docker

**Additional context**
It seems to be for other apps too are having similar issues, such as Readably. 

Here is my NGINX reverse proxy configuration on the host:

```
server {
        server_name rss.domain.com;

        location / {
                proxy_set_header   X-Real-IP         $remote_addr;
                proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header   Host              $host;
                proxy_set_header   X-Forwarded-Proto $scheme;

                # websockets
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";

                proxy_pass http://127.0.0.1:8489/;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/rss.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rss.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

Thank you.

**Comment by Frenzie** [comment]
In Settings → Profile → API management it should mention the URL you need. I.e., that's almost certainly `rss.whatever.com` **/api** , possibly `api/greader.php`.

**Comment by binarydad** [comment]
Thank you. It seems the issue was I needed to set the password for the API user.

![image](https://user-images.githubusercontent.com/1760607/145244653-b3b8c300-0f44-481d-bf23-7f1107e64b25.png)
