### ISSUE TITLE
[BUG] global view: loading wheel

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#4047]
**Describe the bug**

**To Reproduce Step 1**
1. go to global view (https://demo.freshrss.org/i/?a=global)
![grafik](https://user-images.githubusercontent.com/1645099/145263708-ae4fad6a-af96-47fd-baae-269b48d51b37.png)

2. chose a category (f.e. comics)
 
![grafik](https://user-images.githubusercontent.com/1645099/145263867-095401f7-d9b7-4663-a81a-a5c4f574595a.png)

**Expected behavior 1**
it does not load automatically the next items.

**To Reproduce Step 2**
When you click on "load more articles":
the loading wheel does not disappear and a error is shown in the console
![grafik](https://user-images.githubusercontent.com/1645099/145264174-4e9c9cd8-a6ee-4645-82bf-f93300bc0a54.png)

**Environment information (please complete the following information):**
demo.freshrss.org (V1.18.1)

**Comment by math-GH** [comment]
All views uses `.\app\views\helpers\pagination.phtml`
In normal view and reader view it is not an issue, but in global view.

I cannot find the answer. It is difficult to investigate. 

The shown error is not the root problem. Take a look into main.js load_more_post.js

**Comment by yzqzss** [comment]
This bug is also happened on latest Edge version(1.19.0-dev):

| View mode | logged | **anonymous** |
| --- | --- | --- |
| Normal | OK | **Error** |
| Global | **Error** | **Error** |
| Reader | OK | **Error** |

In anonymous mode, this bug is even more serious.
