### ISSUE TITLE
Typo on Update 02_First_steps.md [BUG]

### ISSUE THREAD

**Issue by happymacarts** [marienfressinaud/FreshRSS#4050]
**Describe the bug**
There is a typo on Update 02_First_steps.md line 11 "availalbe"

**To Reproduce**
View page

**Expected behavior**
"Available"

**Additional context**

**Comment by Frenzie** [comment]
Thanks for the report. At a glance I don't see it here, or do you mean another file? 

https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/developers/02_First_steps.md

**Comment by happymacarts** [comment]
FreshRSS/docs/en/users/02_First_steps.md
