### ISSUE TITLE
[Feature] Want every article has spearate url to make the site looks like a news website.Can we do this or have any plugin can do this ?

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [marienfressinaud/FreshRSS#4053]
[Feature] Want every article has spearate url to make the site looks like a news website
Can we do this or have any plugin can do this ?

**Comment by math-GH** [comment]
Could you please explain what is your use case?

**Comment by ZhaoGuangYue1986** [comment]
> 

I want to make my rss site look like a news site for all people ,and make the artical More friendly to search engines

**Comment by Alkarex** [comment]
In the core, we could add a search function showing only the article(s) matching the provided ID(s).
The rest should be an extension, to e.g. change the links in the user interface

**Comment by math-GH** [comment]
The search engines, f.e. Google, will not accept it. It will mark your content as duplicate content. There is no benefit for you.

In Germany (maybe also in whole Europe) you could get into troubles to republish content from other pages because of copy rights

**Comment by Alkarex** [comment]
Indeed, republishing content without permission might lead to various problems, as @math-GH writes.
But for a closed system, that might be fine.
Note that by default, FreshRSS blocks search engines (meta robots instruction).

I have just implemented the core feature of searching by article IDs, which might be useful for various extensions
https://github.com/FreshRSS/FreshRSS/pull/4058

**Comment by BrodyStone21** [comment]
I've been thinking the same thing but simply for sharing articles with others. I'm running FreshRSS through a reverse proxy and can access it via news.mydomain.com

I'd like to be able to share articles on my site without actually linking to the external source.

**Comment by Alkarex** [comment]
Using the reading view and the new entry ID filter, it is now possible to achieve something like that:
![image](https://user-images.githubusercontent.com/1008324/147823921-136bffb7-cd5b-4c0d-b9a2-b46722c13543.png)
