### ISSUE TITLE
[BUG] Can't filter articles with an older publication date

### ISSUE THREAD

**Issue by danburd** [marienfressinaud/FreshRSS#4057]
**Describe the bug**
Some feeds publish articles with a publication date that is several weeks, months or years in the past, and I do not want them to appear as unread. However, there is no filter that works to mark these read on the feed settings level. Using negative time interval filters should work, but it doesn't work in practice for some reason.

**To Reproduce**
1. Subscribe to Foreign Affairs: https://www.foreignaffairs.com/rss.xml
2. Add the following filter in the feed settings: ```!pubdate:P3d``` (as described in [this issue report](https://github.com/FreshRSS/FreshRSS/issues/3532#issuecomment-802650161))
3. Wait and watch as **all** articles that are published are marked as read, not just those with a publication date more than three days in the past.

**Expected behavior**
Only articles with a publication date more than three days in the past should be marked as read. This is what is shown when you conduct a search within that feed. For some reason, applying the filter at the feed settings level captures all articles erroneously.

**Environment information (please complete the following information):**
- FreshRSS version: 1.18.1

**Additional context**
You can also test this on a feed that updates very frequently, to get a quicker result. For some reason, ```!pubdate:P3d``` and other time intervals will mark everything as read even though it logically shouldn't work that way.

```pubdate:/202111``` works, but then I have to keep changing the date as time goes by.

Also - thank you for FreshRSS, which is wonderful and I use it every day.

**Comment by Alkarex** [comment]
@danburd Could you please try this patch https://github.com/FreshRSS/FreshRSS/pull/4092 (not tested yet)

**Comment by danburd** [comment]
Hello, thank you very much for the patch. I'd like to try it but I'm not sure how. I currently use FreshRSS from the Docker package from linuxserver.io.

**Comment by Alkarex** [comment]
@danburd It is not so simple to test in that case, as it requires a bit of Docker manipulations :-)

**Comment by Alkarex** [comment]
@danburd The patch is merged in our edge branch and can be tested for instance with our Docker image `freshrss/freshrss:edge`
https://hub.docker.com/r/freshrss/freshrss/tags

**Comment by danburd** [comment]
Thank you so much, @Alkarex! Happy New Year!
