### ISSUE TITLE
Hide read articles from anonymous reading mode?

### ISSUE THREAD

**Issue by BrodyStone21** [marienfressinaud/FreshRSS#4060]
I've got an instance of FreshRSS set up with several feeds. I'm running FreshRSS through a reverse proxy so I can access it via news.mydomain.com

I've enabled anonymous reading mode so my friends and family can access it and read articles from my feeds. The issue is when in anonymous mode users can tell what articles I've read. I'd like to hide this. Is this a feature that has already been implemented or is it something that can be easily implemented?

If it's not implemented, could I create another user called "public" or "anonymous"  and then share all of my feeds with that user and make that the default anonymous mode user?

**Comment by math-GH** [comment]
The first created user (made in the install routine) is your default user. You cannot change it via the config.

If you allow anonymous reading that you should create another private user for yourself. Unfortunately you cannot sync the feeds to other users.

**Comment by BrodyStone21** [comment]
@math-GH Any possibility of this getting added in the future? Maybe create a user called "public" or something like that and make that the default if you're not logged in and that user can't view opened articles (unless cached or something). Additionally, choosing which feeds that user can view would also be nice.

I don't know exactly what would need to be done, but I think it'd be a nice feature to have.

**Comment by math-GH** [comment]
As always. PRs are welcome ;)

(I cannot support. I am just the frontend guy)

**Comment by math-GH** [comment]
> The first created user (made in the install routine) is your default user. You cannot change it via the config.
> 

I found how to change your default user:

There is no UI for changing the default user, but a CLI (`./cli/reconfigure.php --default_user YourNewAdmin`) is provided. It can also be changed manually by editing the text file `./FreshRSS/data/config.php` and changing `'default_user' => 'alice'`, to the desired user.

**Comment by math-GH** [comment]
Is it still a feature request or is it solved with the script to change the default user?

The information how to change the default user is written in the documentation: https://freshrss.github.io/FreshRSS/en/admins/13_Default_user.html
