### ISSUE TITLE
Blast! Check permissions on the /tmp directory for admin user. The HTTP server must have write permissions.

### ISSUE THREAD

**Issue by jegornagel** [marienfressinaud/FreshRSS#4062]
**Describe the bug**
I'm following the guide [here](https://freshrss.github.io/FreshRSS/en/admins/03_Installation.html) and got the error: 
`Blast! Check permissions on the /tmp directory for admin user. The HTTP server must have write permissions.`

**Environment information (please complete the following information):**
- OS: 18.04.6 LTS , server
- Browser: Firefox 95.0
- Database version: 5.7.36, for Linux (x86_64)
- PHP version: 7.2.24-0ubuntu0.18.04.10, is compatible with FreshRSS.
- Installation type: https://freshrss.github.io/FreshRSS/en/admins/03_Installation.html

**Comment by Alkarex** [comment]
Hello,
The error is explicit. Have you done anything special to your `/tmp` directory?

```sh
ls -alh /tmp/
```

Ideas of solutions:

* You can try to fix your `/tmp/` directory permissions
* Make a `./FreshRSS/constants.local.php` file:

```php
<?php
define('TMP_PATH', '/your/custom/tmp/path');
```

* Use our official Docker image

**Comment by jegornagel** [comment]
Thanks for a prompt responce. Unfortunately, I couldn't manage to solve the problem. Permissions for /tmp/ set correctly. I even made a constants.local.php but it now says  `Check permissions on the /my/custom/tmp/path directory `. Will try clean install. Thank you!
