### ISSUE TITLE
[BUG] Article Time Being Cut Off in Main Feed

### ISSUE THREAD

**Issue by BrodyStone21** [marienfressinaud/FreshRSS#4064]
Hello, I was hoping someone here could help me out with a super tiny issue that is driving me nuts. For some reason, when I'm using Firefox on Ubuntu, I'm having issues with seeing the article time in the main feed. I don't know exactly what's causing the issue but I believe it is the font size. If I reduce my font size from 18 to 16 I can see a little more, but it's not easy for me to read that way. 

Font size 18
![Screenshot from 2021-12-13 16-24-43](https://user-images.githubusercontent.com/36679309/145891222-fc46d538-486a-4717-bd67-351d85c5b46d.png)

Font size
![Screenshot from 2021-12-13 16-25-33](https://user-images.githubusercontent.com/36679309/145891308-84a47366-ff96-4cbd-865c-269e61d4e2b9.png)
 16

**Comment by math-GH** [comment]
It happens in: language= English (USA), but not in English (UK).

You could fix it with Custom CSS (https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS):
```
.flux .item.date {
width: 180px
}
```

Also Occitan is affected
![grafik](https://user-images.githubusercontent.com/1645099/145893255-87d3670a-782d-49c9-aeeb-dc151babbb08.png)
and Portuguese (Brazil)

**Comment by math-GH** [comment]
Maybe this extension could also solve your problem:
https://github.com/aledeg/xExtension-DateFormat (I did not test it)

**Comment by BrodyStone21** [comment]
>It happens in: language= English (USA), but not in English (UK).

I tried both and the regular "English" widened it slightly but just barely. It was still being cut off. 

>Maybe this extension could also solve your problem:
https://github.com/aledeg/xExtension-DateFormat

I actually have that installed and I'm not sure if I'm not using it correctly or what, but I have noticed no differences. 

>You could fix it with Custom CSS (https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS):

It appears that @Alkarex has added this to 1.20.0 milestone, so I'll just wait until it's fixed. Thanks for the information!

**Comment by math-GH** [comment]
> > Maybe this extension could also solve your problem:
> > https://github.com/aledeg/xExtension-DateFormat
> 
> I actually have that installed and I'm not sure if I'm not using it correctly or what, but I have noticed no differences.

@aledeg could you have a look?

**Comment by math-GH** [comment]
> > You could fix it with Custom CSS (https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS):
> 
> It appears that @Alkarex has added this to 1.20.0 milestone, so I'll just wait until it's fixed. Thanks for the information!

You can install CustomCSS extension right now into 1.18. (it is very easy. Download it and put it into `extension` folder. How to: see https://github.com/FreshRSS/Extensions )

We plan for 1.20 to bring CustomCSS as a system (pre-installed) extension. Right now you have to do it by yourself.

**Comment by math-GH** [comment]
> > Maybe this extension could also solve your problem:
> > https://github.com/aledeg/xExtension-DateFormat
> 
> I actually have that installed and I'm not sure if I'm not using it correctly or what, but I have noticed no differences.
> 

1) install the extension: copy & paste the files into extension folder (final path example: s/extensions/xExtension-Date-Format-main/README.md)
2) go to the settings and enable the extension (the button title is "diasble" when the button is enabled)
![grafik](https://user-images.githubusercontent.com/1645099/146053789-419472d6-e670-4658-b1c1-812e00b5a46b.png)
3) with the "manage" button you can edit the date settings

**Comment by math-GH** [comment]
Till now I do not have a good idea how to fix it best except to do a custom CSS

**Comment by BrodyStone21** [comment]
Closing this because I never got around to messing with this.
