### ISSUE TITLE
[BUG] demo.freshrss.org: theme changed + Hungarian feeeds

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#4070]
Please check demo.freshrss.org

The anonymous user has now not the Origine theme and displays f.e. a Hungarian feed

![grafik](https://user-images.githubusercontent.com/1645099/146643518-49c47f42-6127-48ae-9d58-48ce3efa2a00.png)

Expected:
- Origine theme
- English feeds

**Comment by Frenzie** [comment]
You can log in with demo/demodemo to play around with it. I believe it's automatically reset once an hour or once a day.

**Comment by math-GH** [comment]
Yesterday I saw it too.

**Comment by math-GH** [comment]
let us clarify how often there is a reset..

(I changed the theme back to Origine and deleted the Hungarian feeds right now)

**Comment by Frenzie** [comment]
@marienfressinaud

**Comment by marienfressinaud** [comment]
I reset the demo manually once in a while, mostly when I update the server. I just did it.

Btw, I saw the mentions on the other tickets but I need to take a break from Internet so I'll answer after the holidays.

**Comment by Frenzie** [comment]
No problem. Happy holidays!

**Comment by marienfressinaud** [comment]
I just created a small extension to fill the credentials on the demo instance and to reset the instance every night via a cron task: https://github.com/marienfressinaud/xExtension-Demo

I don't think it should be listed in the https://github.com/FreshRSS/Extensions list, but I will transfer the ownership of the repository to the FreshRSS organization. What do you think?

**Comment by Frenzie** [comment]
Sounds good to me. :-)

(But listing it could perhaps be useful too, for some people? On the flip side, it'd mostly just be noise I suppose.)

**Comment by math-GH** [comment]
I would like to see it in the extension list because every extension could be a good source to develop a new extension.

**Comment by marienfressinaud** [comment]
A better place would be in the developers documentation then, I think the extensions list is more intended to administrators who want to discover extensions (and there are good chances they don't want to install this one :D)

**Comment by Frenzie** [comment]
The "extension" bit seems somewhat… redundant, in any case. It's basically just a sample script that can/should be triggered with cron. The extension around it is just so you've got a reminder in the UI.

**Comment by math-GH** [comment]
@marienfressinaud : Right now it is possible to delete the extension in the demo instance, because the demo user has administrator rights. After the deletion the reset script would not be available.
To mark the extension as system extensions, would not solve this issue. 
Do we need a new flag in metadata.json like `removeButton: false`?

**Comment by marienfressinaud** [comment]
I don't think it's necessary, it's a very specific use case that I wouldn't see generalized. I think I can handle it in the extension itself.

Edit: It should be enough :) https://github.com/FreshRSS/xExtension-Demo/commit/bdbc14ca0fd3164b2dd1ebad704c3d79bbe545d8
