### ISSUE TITLE
[BUG] Advanced option like "Filter actions" are not saved using the export option to fully migrate a configuration

### ISSUE THREAD

**Issue by typhoe** [marienfressinaud/FreshRSS#4077]
**Describe the bug**
"Filter actions" are not saved using the export option to migrate a configuration

**To Reproduce**
1. Go to subscription management and add something to "Filter actions" on one feed subscription, then save
![Filter_Actions](https://user-images.githubusercontent.com/881171/147068944-16b171fd-5c6c-4932-bb69-281f890b6c0b.png)
2. Go to "Import / Export" and export all your conf (here are extract with only the parts about that feed)
[feed_2021-12-22_8_114.json.txt](https://github.com/FreshRSS/FreshRSS/files/7761534/feed_2021-12-22_8_114.json.txt)
[feeds_2021-12-22.opml.xml.txt](https://github.com/FreshRSS/FreshRSS/files/7761608/feeds_2021-12-21.opml.xml.txt)
3. Restore that conf on another FreshRSS install with the "Import" option
4. See that the "Filter actions" stays empty (the info doesn't even seem to be in the exported opml.xml file)

**Expected behavior**
Exporting all the configuration of the feed subscriptions (so also all fields modified, not only "Filter actions" if there are others) 

**Environment information (please complete the following information):**
Export done on FreshRSS 1.19.0-dev (git) in a LXC container running debian OS with postgreSQL DB, import in FreshRSS official Docker alpine tag sqlite DB

**Comment by typhoe** [comment]
Just saw that indeed, other options are not saved either.

For ex:
![option](https://user-images.githubusercontent.com/881171/147071288-ba96073c-4615-4429-91ea-c5e9e8ab6a68.png)

That was also not exported

**Comment by Alkarex** [comment]
The method using export-to-SQLite / import-from-SQLite should include all those aspects. See https://github.com/FreshRSS/FreshRSS/tree/edge/cli
Exports using standard formats (OPML, Google Reader format) indeed do not export those custom aspects.

**Comment by typhoe** [comment]
Hum, ok. 

In my case, I already copied/pasted all the advanced settings manually.... but would the "export-sqlite-for-user.php" have worked as my database was MariaDB?

And maybe add a message in the "import/export" menu to warn users that these settings won't be in the zip exported when using the website ?

**Comment by Alkarex** [comment]
Test of https://github.com/FreshRSS/FreshRSS/pull/4342 welcome
