### ISSUE TITLE
[BUG] Errors on login page, when user is unknown

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#4080]
**Describe the bug**
Try to login with a unknown username.

In development mode, there are some errors

**To Reproduce**
1. run in development mode (data/config.php)
2. Login page
3. try to login with a unknown username
4. see the error

**Expected behavior**
no error message

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1645099/147275899-bed2db60-98b0-43d9-854f-d2584ed70e4d.png)

![grafik](https://user-images.githubusercontent.com/1645099/147276549-833f28c5-f786-44bb-8354-29239d4d11cc.png)

![grafik](https://user-images.githubusercontent.com/1645099/147275929-88e38f07-1504-4872-a17d-20f5c07f9d65.png)

**Environment information (please complete the following information):**
- OS: XAMP on Windows
- FreshRSS version: 1.19.0-dev
- Database version: MySQL
- PHP version: PHP 7.4
- Installation type: XAMP

**Additional context**
development mode

**Comment by math-GH** [comment]
a root of this issue could be, that in this case `FreshRSS_Context::$user_conf` is not initialized

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/4081
