### ISSUE TITLE
[Docker] Support for raspberry pi OS 64 bit

### ISSUE THREAD

**Issue by PolGZ** [marienfressinaud/FreshRSS#4089]
Tried both `freshrss:arm` and `freshrss:arm` and `:latest-arm`, both get:

```
WARNING: The requested image's platform (linux/arm) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
Searching in [docker-tags](https://hub.docker.com/r/freshrss/freshrss/tags) it doesn't seem to be an ARM64 version.

**Comment by Alkarex** [comment]
Updates on how to perform multi-platform builds on Docker Hub welcome (e.g. `buildx`).
At the moment, our auto-builds are done with qemu https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/hooks/pre_build

**Comment by PolGZ** [comment]
> Updates on how to perform multi-platform builds on Docker Hub welcome (e.g. `buildx`). At the moment, our auto-builds are done with qemu https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/hooks/pre_build

I have no experience with docker (this was my second time using a docker) and no programming experience at all, so I don't really know what to do with that. I'll use another rss server for now, but thank you very much for the reply. I'm looking forward to that v. 1.20!

**Comment by Alkarex** [comment]
@PolGZ You can give a try to this unofficial Docker image, which supports more architectures https://hub.docker.com/r/linuxserver/freshrss

**Comment by math-GH** [comment]
How is the status?

**Comment by honnip** [comment]
```bash
#!/bin/bash

if [[ $DOCKERFILE_PATH == *-ARM ]]; then
	# https://github.com/balena-io/qemu
	# Download a local copy of QEMU on Docker Hub build machine
	curl -LSs 'https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz' | tar -xzv --strip-components=1 --wildcards '*/qemu-*'

	# https://github.com/multiarch/qemu-user-static
	# Register qemu-*-static for all supported processors except the current one, but also remove all registered binfmt_misc before
	docker run --rm --privileged multiarch/qemu-user-static:register --reset
fi

if [[ $DOCKERFILE_PATH == *-ARM64 ]]; then
	# https://github.com/balena-io/qemu
	# Download a local copy of QEMU on Docker Hub build machine
        # qemu-7.0.0.balena1-aarch64.tar.gz
	curl -LSs 'https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-aarch64.tar.gz' | tar -xzv --strip-components=1 --wildcards '*/qemu-*'

	# https://github.com/multiarch/qemu-user-static
	# Register qemu-*-static for all supported processors except the current one, but also remove all registered binfmt_misc before
	docker run --rm --privileged multiarch/qemu-user-static:register --reset
fi
```
I made a tiny progress 🙃 


By the way, I could easily create a multi arch image with GitHub Action like [here](https://github.com/honnip/caddy-cloudflare/blob/main/.github/workflows/main.yml).

**Comment by lazyzyf** [comment]
> @PolGZ You can give a try to this unofficial Docker image, which supports more architectures https://hub.docker.com/r/linuxserver/freshrss

why the official image does not support more platform.such as arm64?

**Comment by Alkarex** [comment]
> why the official image does not support more platform.such as arm64?

Because as far as I know, there is no native multiplatform support in Docker Hub at the moment, and the QEMU-based workaround we have for arm32v7 is quite heavy.

* https://github.com/docker/hub-feedback/issues/1874
* https://github.com/docker/roadmap/issues/109#issuecomment-1195366445

If anyone becomes aware of a better method than what we are using at the moment, let us know.

* https://github.com/FreshRSS/FreshRSS/tree/edge/Docker/hooks
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/Dockerfile-QEMU-ARM

It is quite easy to build locally for any platform: https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#build-custom-docker-image
(and I could provide a docker-compose example)

**Comment by Alkarex** [comment]
Related discussion https://github.com/FreshRSS/FreshRSS/discussions/5078

**Comment by Aevrin** [comment]
Just wanted to add to this request.  It looks like docker.io supports multiarch under the same tag, and can be configured to build using github actions (I'm no expert in this, but have managed it with a personal project.).  I just used buildx and selected the platforms I needed.  Could that be offered?  The arm7 works fine, but having it offered under one tag would be helpful, as would the arm64 offering.

![2023-04-20_22-16](https://user-images.githubusercontent.com/73451165/233525215-6f559151-f401-4575-96d8-8ecc31350f8c.png)
![2023-04-20_22-15](https://user-images.githubusercontent.com/73451165/233525233-6e1d6b69-ecbc-4f13-a60d-3c6518ed8f6d.png)


platforms: linux/amd64,linux/arm64/v8

**Comment by maxdemaio** [comment]
> If anyone becomes aware of a better method than what we are using at the moment, let us know.

I've created a GitHub action in the past that will automatically push multi-platform images to Docker Hub. The example of this is here https://github.com/maxdemaio/hooligans-hangman-bot/blob/main/.github/workflows/docker-image.yml. Specifically in the `docker/build-push-action@v3` action you can give it a `platforms` array like `platforms: linux/amd64,linux/arm64`.

Please feel free to let me know if this isn't the right idea. I'd be glad to contribute to the repository and try to make a PR with changes! We could specify the action to run on certain events like the publishing of a release and it would automatically push the tagged docker images to docker hub 👍🏻

**Comment by b-reich** [comment]
@Alkarex I could provide an PR for this. Where are the images built? I could offer actions on Github.

**Comment by Alkarex** [comment]
@b-reich Excellent 👍🏻  Images are built on Docker Hub at the moment

**Comment by lazyzyf** [comment]
why no arm46 support in docker hub?

**Comment by Alkarex** [comment]
> why no arm46 support in docker hub?

With the new build system, it is probably easy, and could indeed be popular addition.
Note that we already document a docker-compose with auto-build for any platform

**Comment by b-reich** [comment]
> why no arm46 support in docker hub?

Take a look at #5808 😃

**Comment by fn-ix** [comment]
Still getting the same error as the OP after pulling the latest version and executing the quick run command with `... freshrss/freshrss:arm`. Am I missing something?

**Comment by Alkarex** [comment]
@fn-ix please try `freshrss/freshrss`
