### ISSUE TITLE
Global filtering in 1.19 missing?

### ISSUE THREAD

**Issue by githupper** [marienfressinaud/FreshRSS#4106]
Hi,

I understand that it was mentioned 1.19 will have the capability to perform filtering of articles on a global or category basis rather than on a per feed level as was in 1.18.

With the new release of 1.19, I was unable to find any such capability. Please advise how to do so or the global filtering capability has been pushed to a later version?

Thank you

**Comment by Alkarex** [comment]
Indeed, there has been so many other things that this feature has been delayed https://github.com/FreshRSS/FreshRSS/issues/2788
But it is also high on my own wish-list :-)

**Comment by githupper** [comment]
Got it. Thank you for the support. Will keep a lookout for it in 1.20.0 changelog.
