### ISSUE TITLE
some feeds don't show the thumbnail

### ISSUE THREAD

**Issue by math-GH** [marienfressinaud/FreshRSS#4111]
<img width="711" alt="freshrsstech" src="https://user-images.githubusercontent.com/54511555/147856675-270d61dd-5a94-4432-9eb5-e6a07bec6ac0.png">

Any ideas on why some feeds don't show the thumbnail?

Feed: https://feeds.feedburner.com/VideoCardzcom
Website: https://videocardz.com/

Edit: Apologies in advance if I should open a new issue instead?

_Originally posted by @Hukuma1 in https://github.com/FreshRSS/FreshRSS/issues/4078#issuecomment-1003591065_

**Comment by math-GH** [comment]
@hukuma1: As I see there is not thumbnail in the Atom feed. That is why no thumbnail is displayed. 

Extended technical explanation: 
Atom 1.0 does not support thumbnails by default. There is an unofficial extension by Yahoo. https://rehansaeed.com/building-rssatom-feeds-for-asp-net-mvc/

**Comment by Hukuma1** [comment]
Ah thank you. I got confused initially because I even clicked the `Check the validity of the feed` button and it said valid RSS feed.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeeds.feedburner.com%2FVideoCardzcom

**Comment by Frenzie** [comment]
I think most feeds probably don't have thumbnails? I could be mistaken, but in any case it's optional. :-)
