### ISSUE TITLE
PHPStan level 6

### ISSUE THREAD

**Issue by Alkarex** [marienfressinaud/FreshRSS#4112]
PHPStan is an automated scanner, which reports code that could be improved https://phpstan.org

We already pass PHPStan level 5 since https://github.com/FreshRSS/FreshRSS/pull/4110

Usage:

```sh
# See https://getcomposer.org
composer install --prefer-dist
composer run-script phpstan
```

Now it would be nice to progress to PHPStan level 6 *report missing typehints* https://phpstan.org/user-guide/rule-levels

https://github.com/FreshRSS/FreshRSS/blob/1335a0e3cf11a0d4248e9eaaf748b89e6df741ef/phpstan.neon#L2-L3

```sh
# Manual override of the analyse level
vendor/bin/phpstan analyse . --level 6
```

Help welcome, and it is fine to send multiple PRs, each solving some of the PHPStan warnings (best if covering at least one or more files fully).

When you make more files pass Level 6, you can remove them ([example](https://github.com/FreshRSS/FreshRSS/commit/a5cc7b20f6b05ceae73a90dc418345f7f0dede6f)) from our [list of non-compliant files](https://github.com/FreshRSS/FreshRSS/blob/edge/tests/phpstan-next.txt) (cf. https://github.com/FreshRSS/FreshRSS/pull/5230 )

```sh
composer run-script phpstan-next
```

**Comment by math-GH** [comment]
Are we already on level 6 with 1.20.0-dev?

**Comment by Alkarex** [comment]
> Are we already on level 6 with 1.20.0-dev?

Nope, we are currently at level 5:

https://github.com/FreshRSS/FreshRSS/blob/0ec3874620c03b03a5cb462d99d710bd802d06f9/phpstan.neon#L3
