### ISSUE TITLE
[BUG]Error during context user init!

### ISSUE THREAD

**Issue by inescafe** [marienfressinaud/FreshRSS#4115]
After following the tutorial at https://freshrss.github.io/FreshRSS/en/admins/06_LinuxInstall.html and go to webpage configuring the database successfully, I went to the url/i/ page and when I logged in for the first time, I was only prompted with“ Error during context user init!" Please help me to solve this problem, thank you!

**Comment by Frenzie** [comment]
Are the write permissions set up correctly? (Although I think the installer should check.)

**Comment by thejudge22** [comment]
I got this error as well after updating my docker for an already existing/functioning install.  3rd party clients still login correctly with the API password, just get this error when going to the login page.  Tested different browsers and incognito as well.

ETA:  I reverted to the previous tag in the docker image and it worked as expected so something changed with the latest update.

**Comment by Alkarex** [comment]
@thejudge22 Which Docker tags are you using? Do you maybe have a docker-compose you could share?

**Comment by Alkarex** [comment]
@inescafe Can you please provide a bit of information about your platform? (OS, database, versions...)

**Comment by thejudge22** [comment]
> @thejudge22 Which Docker tags are you using? Do you maybe have a docker-compose you could share?

I'm using the Linuxserver docker release: linuxserver/freshrss:1.18.1 right now that works.

Using the default latest tag with the 1.19 release causes the issue.

I tried a fresh docker install with a new data directory and after the installation process it gives the same error.

It's running on Unraid which doesn't use docker-compose by default.  Here's the docker run:  /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='freshrss' --net='bridge' -e TZ="America/Chicago" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -p '32007:80/tcp' -v '/mnt/user/appdata/freshrss':'/config':'rw' 'linuxserver/freshrss:1.18.1'

**Comment by inescafe** [comment]
> @inescafe Can you please provide a bit of information about your platform? (OS, database, versions...)

OS:Ubuntu 20.04.3 LTS \n \l
database:mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
versions: Use the command: "git clone https://github.com/FreshRSS/FreshRSS.git", which should be the latest version.
PHP:7.4
freshrss error log suggest：[Sun Jan 02 08:40:04.776359 2022] [php7:notice] [pid 1283] [client (IP):13443] PHP Notice:  Undefined index: $SQL_CREATE_TABLES in /usr/share/FreshRSS/app/Models/UserD></UserDAO.php on line 8, referer: http://url/i/index.php?step=3

**Comment by Alkarex** [comment]
Thanks @inescafe , error found.

**Comment by Alkarex** [comment]
@inescafe Patch https://github.com/FreshRSS/FreshRSS/pull/4116 landed in our `edge` branch. Can you please `git pull --ff-only` and try again?

@thejudge22 I will make a new release 1.19.1. Meanwhile, would you be able to try the image `freshrss/freshrss:edge` ?

**Comment by inescafe** [comment]
> git pull --ff-only

It works!Thank you!
But it needed to be reset, and not knowing how to do it, I deleted . /data/, remake and re-authorized, went to the web, set mysql information, and it worked!

**Comment by thejudge22** [comment]
> @thejudge22 I will make a new release 1.19.1. Meanwhile, would you be able to try the image `freshrss/freshrss:edge` ?

Confirmed resolved in 1.19.1 docker release.
