### ISSUE TITLE
[BUG]Issue install 1.19.1

### ISSUE THREAD

**Issue by hdegorce** [marienfressinaud/FreshRSS#4118]
Hello,
I tried to install the last version but there is an issue, once i go in the website: "Error during context user init!"
Here is the script:
```
wget -O- https://github.com/FreshRSS/FreshRSS/archive/1.19.1.tar.gz | tar -xz --strip-components=1

./cli/do-install.php --default_user admin --auth_type form --environment production --base_url https://$INSTALL_URL --language "$LANGUAGE" --title "$TITLE" --db-type mysql --db-host "$DATABASE_HOST":3306 --db-user "$DATABASE_USERNAME" --db-password "$DATABASE_PASSWORD" --db-base "$DATABASE_NAME"

./cli/create-user.php --user "$USERNAME" --password "$PASSWORD"
```

I tried with PHP 8.0 and PHP 7.4. and it's Apache server and Debian. The last 1.18 is working well

**Comment by guorenxi** [comment]
Same here.

**Comment by Alkarex** [comment]
Would you mind trying with our current edge version? Using e.g. git https://github.com/FreshRSS/FreshRSS.git or an archive https://github.com/FreshRSS/FreshRSS/archive/edge.tar.gz (or ZIP)

**Comment by Alkarex** [comment]
So far, I cannot reproduce the problem. Make sure that you are creating the default user. Maybe by changing your second command by:

```sh
./cli/do-install.php --default_user "$USERNAME" ...
```

**Comment by hdegorce** [comment]
Thanks, I had the same issue with the edge version but by indicating directly $USERNAME instead of admin in the ./cli/do-install.php it's working.

**Comment by seniyakk** [comment]
Hello.
I have same issue "Error during context user init!". But I am using docker compose. 
I have next  fields:

>  FRESHRSS_INSTALL: |-
>         --api_enabled
>         --base_url /
>         --db-host freshrss_postgres:5432
>         --db-base freshrss
>         --db-user freshrss
>         --db-password freshrss
>         --db-type pgsql
>         --default_user root
>         --language en
>       FRESHRSS_USER: |-
>         --api_password admin
>         --email admin
>         --language en
>         --password admin
>         --user admin

As I understood I need specify --default_user field. What user name or host machine, docker, root, some other user from container I need to use?

In logs I see next:

> ℹ️ FreshRSS already installed; no change performed.
> FreshRSS warning: username already exists “admin”
> ℹ️ FreshRSS user already exists; no change performed.

When I change name on other one I see same mistake

> ℹ️ FreshRSS already installed; no change performed.
> FreshRSS warning: username already exists “root”
> ℹ️ FreshRSS user already exists; no change performed.

Thanks

**Comment by Alkarex** [comment]
@seniyakk Please open a new issue instead. See already https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#docker-compose

**Comment by myido** [comment]
/data/config.php

default_user ='新创建的用户名'
