### ISSUE TITLE
[BUG] Trailing slash apache2 reverse proxy subpath

### ISSUE THREAD

**Issue by Crashillo** [marienfressinaud/FreshRSS#4126]
**Describe the bug**
Depending on the final trailing slash, the application will load successfully or not. 

**To Reproduce**
FreshRSS is running under a subpath, and the following happens:
`example.org/rss/` **OK**, freshrss redirects to `example.org/rss/i/`
`example.org/rss` **FAIL**, freshrss redirects to `example.org/i/` and the `<Location>` apache directive doesn't match the path

**Expected behavior**
Both entries should load the application in the same way

**Environment information (please complete the following information):**
- FreshRSS version: 1.19.1
- Installation type: Docker (image `freshrss/freshrss:arm`)
- Server: Apache 2.4
 
**Additional context**
Reverse proxy configuration file:
```
ProxyPreserveHost On

<Location /rss >
#  RewriteCond %{REQUEST_URI} /+[^\.]+$
#  RewriteRule ^(.+[^/])$ %{REQUEST_URI}/ [R=301,L]
  ProxyPass http://127.0.0.1:8079/
  ProxyPassReverse http://127.0.0.1:8079/
  ProxyPassReverseCookiePath  /  /rss/

  RequestHeader set X-Forwarded-Prefix "/rss"
  RequestHeader set X-Forwarded-Proto "https"

  Require all granted
  Options none
</Location>
```

If I uncomment the _Rewrite_ lines it's even worst, as the `example.org/rss/` becomes `403 Forbidden` and `example.org/rss` still redirecting to `example.org/i/`

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/4167 ?
For convenience, I have also pushed a test image to Docker Hub: `freshrss/freshrss:edge-arm-4126`

**Comment by Crashillo** [comment]
Nope, same situation. If there's no trailing slash, keeps ignoring the subpath, redirecting to `example.org/i/?rid=61eb08c32665f` (it appends the queryparam, as a difference). The rewrite rule doesn't help neither

**Comment by Alkarex** [comment]
I will try a bit more.
For the record, Apache can also be explicit, with e.g. https://httpd.apache.org/docs/current/mod/mod_dir.html#directoryslash
P.S. the reverse proxy rules could also fix the problem, e.g. `<Location /rss/>`, but I will try to see if I can make the internal detection a bit smarter

**Comment by Crashillo** [comment]
I tried `DirectorySlash` directive, but it did nothing. `<Location /rss/>` is not what I want, since apache cannot reach `/rss` due to this one is unhandled.
The point is about the base_path, currently when the application loads, it always appends the subpath `/i/` to the url. However, when there's no trailing slash, it overrides the last subpath. I did a test using `example.org/fake/rss`, it redirects to `example.org/fake/i/`, just ignores the last path

**Comment by Alkarex** [comment]
Regarding `<Location /rss/>`, if you want `<Location /rss>` to also work, you can add such a section in your Apache with a redirection to `/rss/`
Nevertheless, I will try to see I can do something smarter at FreshRSS level to detect such cases.

**Comment by Alkarex** [comment]
I have improved https://github.com/FreshRSS/FreshRSS/pull/4167
Please try again `freshrss/freshrss:edge-arm-4126`

If you remove the trailing slash in Location, do the same in the ProxyPass lines:

```apache
<Location /freshrss>
	ProxyPass http://127.0.0.1:8080
	ProxyPassReverse http://127.0.0.1:8080
	RequestHeader set X-Forwarded-Prefix "/freshrss"
	RequestHeader set X-Forwarded-Proto "http"
	Require all granted
	Options none
</Location>
```

Watch out if you have a `./FreshRSS/data/config.php` from a previous installation, which might contain a `base_url`

**Comment by Crashillo** [comment]
Initially, that's worse. Now when the server matches the url, it removes the subpath, no matter the trailing slash. So, I set my subpath as `'base_url' => 'http://pi2:8079/rss',` in my `config.php` file, and then it works! Both paths start the app properly. Is that the way to proceed?

Btw, the trailing slashes in the reverse proxy file, I didn't notice anything (I'm still using the file I posted at the top).

**Comment by Alkarex** [comment]
`'base_url'` is a way to manually set the base URL. It is automatically detected during install.
If you have the possibility, it would be nice to try an install again with your setup, to check whether that works from scratch

**Comment by Crashillo** [comment]
I just did it from scratch, but unfortunately the new `config.php` file doesn't get the subpath properly. If the url is _example.org/rss_ the `base_url` parameter of the recent created config file, only contains _example.org_

**Comment by Alkarex** [comment]
Could you please post again the Apache conf you tested with?

**Comment by Crashillo** [comment]
I updated my current conf in the initial post (there wasn't a blank space just before the closing tag `<Location /rss >`)
I also tried removing the final slash in the proxy lines, but, as I said, I did notice nothing.
```
  ProxyPass http://127.0.0.1:8079/
  ProxyPassReverse http://127.0.0.1:8079/
```

**Comment by Alkarex** [comment]
@Crashillo I cannot immediately reproduce the problem after my latest fixes. Could you please try again, making sure you `docker pull freshrss/freshrss:edge-arm-4126` first to get the newest image, and making sure to use `X-Forwarded-Prefix` like in the following:

```apache
<Location /freshrss>
	ProxyPass http://127.0.0.1:8080
	ProxyPassReverse http://127.0.0.1:8080
	RequestHeader set X-Forwarded-Prefix "/freshrss"
	RequestHeader set X-Forwarded-Proto "http"
	Require all granted
	Options none
</Location>
```

**Comment by Crashillo** [comment]
Great! I did a fresh install: different docker data folders, different apache conf, and different path. After complete the wizard, everything is set properly, and both url (w/ & w/o trailing slash) redirect as expected. `base_url` parameter, also fulfilled with the subpath. :+1:
