### ISSUE TITLE
[Feature] Use the composer autoloading and the namespaces

### ISSUE THREAD

**Issue by ColonelMoutarde** [marienfressinaud/FreshRSS#4129]
**Describe the solution you'd like**
to continue to modernize the code base of the project, the switch to namespaces and autoloading of composer seems to me a good idea and a track to follow

**Describe alternatives you've considered**
This is a suggestion, and I am ready to discuss it with you (in French on framateam) if you want.

**Comment by Alkarex** [comment]
Please split the concerns in different issues. Namespaces have been discussed and are a no for now. Adding the needed PHP extensions in `composer.json` is fine, PR welcome. We do not have libraries to load via composer.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/discussions/4317#discussioncomment-2586621
