### ISSUE TITLE
SQLite database location

### ISSUE THREAD

**Issue by Antoine2tt** [marienfressinaud/FreshRSS#4132]
Hello,

Just started to use FreshRSS with Docker, i choosed SQLite.

I'd like to know where does the SQLite file is stored? i saw nothing under the "data" folders built with my Docker Compose.

Thank you

**Comment by Alkarex** [comment]
Hello,
Show your docker run, or docker-compose. You might have a docker volume.

Try:

```sh
docker exec freshrss sh -c 'ls /var/www/FreshRSS/data/users/*/db.sqlite'
```

**Comment by Antoine2tt** [comment]
> Hello, Show your docker run, or docker-compose. You might have a docker volume.
> 
> Try:
> 
> ```shell
> docker exec freshrss sh -c 'ls /var/www/FreshRSS/data/users/*/db.sqlite'
> ```

Hello !

Bon j'ai vu que vous étiez français ça ira plus vite,

Je cherchais le répertoire mais j'avoue avoir oublié de vérifier le dossier "users", je trouvais pas ça "logique" de mettre ça dedans, mais j'ai bien trouvé le fichier ! Merci à vous

Bonne journée ^^
