### ISSUE TITLE
[BUG] non-UTF8MB4 database : Emojis not visibles in feed title

### ISSUE THREAD

**Issue by lapineige** [marienfressinaud/FreshRSS#4139]
**Describe the bug**
When a feed contains an emoji, it is displayed properly when the feed is unfolded, but it does not appear properly in the title. Instead there is "??".

Note that not all emojis are causing trouble : I noticed that ":bangbang:" works.

**To Reproduce**
- add a feed that will contain an emoji
- the emoji is replaced by a ?? in the title

**Expected behavior**
The emoji is properly shown.

**Screenshots**

**Environment information (please complete the following information):**
Using Firefox (recent and old versions), any OS shows the same behavior.
- FreshRSS version: latest
- Database version: TODO
- PHP version: TODO
- Installation type: Yunohost

**Comment by Frenzie** [comment]
Might be related to https://github.com/FreshRSS/FreshRSS/issues/2770

**Comment by Alkarex** [comment]
What database are you using? It could be a sign of MySQL not using the full UTF8MB4

**Comment by Alkarex** [comment]
And do you have an example of feed?

**Comment by lapineige** [comment]
I'm using MariaDB (Yunohost configured it), I'm searching for the exact version.

Any twitter/nitter or mastodon feed that contains emojis is affected on my side.

**Comment by Alkarex** [comment]
Could you please provide a concreate example of feed?

**Comment by lapineige** [comment]
Sorry, here it is : if you take that feed https://nitter.fdn.fr/GuillaumeRozier/rss, this particular message for instance https://nitter.fdn.fr/GuillaumeRozier/status/1480075552551849984#m is displayed as "??".

I checked using Firefox (an extension in fact), the emoji is here in the feed.

**Comment by Alkarex** [comment]
I get a 404 *User "GuillaumeRozier" not found*. Another example?

```sh
curl -v 'https://nitter.fdn.fr/GuillaumeRozier/rss'
```

**Comment by lapineige** [comment]
Nitter instance failing I guess. You may try again (it's working now for me), or use https://nitter.42l.fr instead for instance.

**Comment by Alkarex** [comment]
It looks all good on my side:
![image](https://user-images.githubusercontent.com/1008324/148751166-499f2a7b-ffd5-43e3-a1d8-19909c329e05.png)

Tested with MariaDB (and also MySQL, SQLite, PostgreSQL)

Try to check your MariaDB version and configuration. In particular, check the `utf8mb4` settings, see below.
Otherwise, it might be a PHP misconfiguration, e.g. some extensions missing (maybe `php-intl`, `php-mbstring`)

https://github.com/FreshRSS/FreshRSS/blob/3502e50cb24177f06900389f10d265529a24fd58/Docker/Dockerfile#L11-L12

SQL Test:

```sql
SHOW TABLES;
SHOW CREATE TABLE lapineige_entry;
```

```
| freshrss_freshrss_entry | CREATE TABLE `freshrss_freshrss_entry` (
  `id` bigint(20) NOT NULL,
  `guid` varchar(760) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `author` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content_bin` mediumblob DEFAULT NULL,
  `link` varchar(1023) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `date` int(11) DEFAULT NULL,
  `lastSeen` int(11) DEFAULT 0,
  `hash` binary(16) DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `is_favorite` tinyint(1) NOT NULL DEFAULT 0,
  `id_feed` smallint(6) DEFAULT NULL,
  `tags` varchar(1023) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_feed` (`id_feed`,`guid`),
  KEY `is_favorite` (`is_favorite`),
  KEY `is_read` (`is_read`),
  KEY `entry_lastSeen_index` (`lastSeen`),
  KEY `entry_feed_read_index` (`id_feed`,`is_read`),
  CONSTRAINT `freshrss_freshrss_entry_ibfk_1` FOREIGN KEY (`id_feed`) REFERENCES `freshrss_freshrss_feed` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
```

**Comment by lapineige** [comment]
@Alkarex I don't understand if I should run the whole block in one shoot or not, and if I should use a database name that exists (is this creating a new one ?) or not.

Also, I'm using Yunohost, with other databases in that Mariadb, so I wonder if that would affect them.

Thank you.

**Comment by Alkarex** [comment]
@lapineige 

```sql
-- Use the correct database
USE freshrss;

-- To show your tables.
-- Find the one ending with _entry
SHOW TABLES;

-- Then use that command on the existing table, adapting the name
SHOW CREATE TABLE freshrss_lapineige_entry;
```

**Comment by lapineige** [comment]
Ok, now I understand, I initially thought the second block was a command to run !

```
  `id` bigint(20) NOT NULL,
  `guid` varchar(760) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `author` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `content_bin` blob DEFAULT NULL,
  `link` varchar(1023) CHARACTER SET latin1 NOT NULL,
  `date` int(11) DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `is_favorite` tinyint(1) NOT NULL DEFAULT 0,
  `id_feed` smallint(6) DEFAULT NULL,
  `tags` varchar(1023) COLLATE utf8_unicode_ci DEFAULT NULL,


```

**Comment by Alkarex** [comment]
`utf8_unicode_ci` is wrong. We do declare UTF8MB4 in FreshRSS, so there seems to be something wrong in your MariaDB setup:

https://github.com/FreshRSS/FreshRSS/blob/3502e50cb24177f06900389f10d265529a24fd58/app/SQL/install.sql.mysql.php#L3

https://github.com/FreshRSS/FreshRSS/blob/3502e50cb24177f06900389f10d265529a24fd58/app/SQL/install.sql.mysql.php#L40-L61

**Comment by lapineige** [comment]
Do you know if there is a way to convert the database ? Would that affect other databases managed by MariaDB ?

**Comment by Alkarex** [comment]
How old is your FreshRSS table, by the way? We added support for that in FreshRSS 1.5.0 (2016-08-29), including automatic migration.
Do you have anything related to utf8mb4 in your FreshRSS logs?

`grep -i 'utf8mb4'  ./FreshRSS/data/users/*/log*`

**Comment by Alkarex** [comment]
@lapineige Yes, see how we did the automatic update to UTF8MB4 back then in FreshRSS 1.5.0 https://github.com/FreshRSS/FreshRSS/pull/1183 , https://github.com/FreshRSS/FreshRSS/blob/1.5.0/CHANGELOG.md (2016-08-29)


```sql
ALTER DATABASE `%2$s` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `%1$scategory` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
UPDATE `%1$scategory` SET name=SUBSTRING(name,1,190) WHERE LENGTH(name) > 191;
ALTER TABLE `%1$scategory` MODIFY `name` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
OPTIMIZE TABLE `%1$scategory`;

ALTER TABLE `%1$sfeed` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
UPDATE `%1$sfeed` SET name=SUBSTRING(name,1,190) WHERE LENGTH(name) > 191;
ALTER TABLE `%1$sfeed` MODIFY `name` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `%1$sfeed` MODIFY `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
OPTIMIZE TABLE `%1$sfeed`;

ALTER TABLE `%1$sentry` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `%1$sentry` MODIFY `title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `%1$sentry` MODIFY `author` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `%1$sentry` MODIFY `tags` VARCHAR(1023) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
OPTIMIZE TABLE `%1$sentry`;
```

The automatic update was removed in FreshRSS 1.15.0 https://github.com/FreshRSS/FreshRSS/pull/2522 , https://github.com/FreshRSS/FreshRSS/releases/tag/1.15.0 (2019-10-31)

**Comment by lapineige** [comment]
I don't remember, it might be older than that… but I did a few migrations (from backups) in the mid-time, I don't know how this could have affected it, especially in Yunohost context. 

> Do you have anything related to utf8mb4 in your FreshRSS logs?

Nothing.

Thank you for the migration tip, I will see if there any Yunohost specific action to do.

**Comment by Alkarex** [comment]
Ok, an old back-up restore could explain the problem. I recommend using our export-to-sqlite and import-from-sqlite command line tool for backups and migrations https://github.com/FreshRSS/FreshRSS/blob/edge/cli/README.md

**Comment by Alkarex** [comment]
I would actually suggest to use the export-to-sqlite and import-from-sqlite now to make sure your database is as it should be

**Comment by Alkarex** [comment]
```sh
cd ./FreshRSS/
cli/export-sqlite-for-user.php --user lapineige --filename /tmp/lapineige.bak.sqlite
```

**Comment by lapineige** [comment]
I realise this comment https://github.com/YunoHost-Apps/freshrss_ynh/issues/137#issuecomment-1010127878 would be more appropriate here (I guess ?), so here is it:

> Export&Import went fine as far as I can tell, but the issue is not fixed.

>Yet the command you gave me (CREATE TABLE …) shows utf8mb4_unicode_ci.

**Comment by Alkarex** [comment]
It will only be fixed for new articles. Regarding old articles, the information is lost.

**Comment by lapineige** [comment]
Alright, I did not understand that.

Thanks for your help ! :)
