### ISSUE TITLE
Where to find assets (icons, etc?)

### ISSUE THREAD

**Issue by simonszu** [marienfressinaud/FreshRSS#4144]
Hi, 
i want to create a FreshRSS integration/recipe for [Ferdi](https://getferdi.com/). For that, i need a SVG with the app icon which will then displayed in Ferdi's menu from where the user can select FreshRSS as a service which they want to use in Ferdi. Can someone provide me a link to or a file containing FreshRSS's logo as an SVG? 

Thank you very much.

**Comment by Frenzie** [comment]
https://github.com/FreshRSS/FreshRSS/tree/3502e50cb24177f06900389f10d265529a24fd58/p/themes/icons

**Comment by Alkarex** [comment]
See in particular those different variants:

* https://github.com/FreshRSS/FreshRSS/blob/edge/p/themes/icons/icon.svg
* https://github.com/FreshRSS/FreshRSS/blob/edge/p/themes/icons/FreshRSS-logo.svg
* https://github.com/FreshRSS/FreshRSS/blob/edge/p/themes/icons/favicon.svg
