### ISSUE TITLE
I created a theme based on Nord's color scheme

### ISSUE THREAD

**Issue by joelchrono12** [marienfressinaud/FreshRSS#4147]
So, the base-theme README file said to share an issue if I made some theme, so I decided to do one, but if there is a bettter way now (like Discussions, but I did not find any themes there) let me know :P 

I basically just changed some colors and icons, and ended up with a decent nord dark theme that finally fits my liking, I am not a CSS expert, I edited everything inside of `template.css` and I still don't understand how to make the left to right versions.

Nonetheless, here is my current progress, and I would appreciate if anyone can help me simplify and fix some bugs, remove duplicate css elements and such. Check it out [here](https://github.com/joelchrono12/freshrss-nord-theme)!

![original](https://user-images.githubusercontent.com/18448587/149184995-035f3ada-f129-4469-8f01-1bb69e63ed9c.png)

**Comment by math-GH** [comment]
Well done :)

Here some tricks to make it more lean:

When you use `template.css` you do not need to use `base.css` (I would say, that the documentation needs to be updated. I do not fix base.css anymore).

`metadata.json`: you could use `"_template.css"` (see the "_"), than it will load the "newest" template.css that we support.

For your changes please create a new CSS file (f.e. "nord.css"), put there in your color schemes and add to the `metadata.json` (  `"files": ["_template.css", "Nord.css"]`).

If you do not change something on an icon, than you could delete the icon file from your `icon ` folder. Icons will be loaded by default from the `themes/icon` folder, when it is not included in your theme.

Be careful with FreshRSS updates. It will delete your custom theme without a warning. Keep a copy somewhere (f.e. in this github repository)

**Comment by Alkarex** [comment]
@joelchrono12 Nice! You are welcome to send a pull request, and we can help you with some technical details to finalise the theme

**Comment by joelchrono12** [comment]
> Nice! You are welcome to send a pull request, and we can help you with some technical details to finalise the theme

Thanks for the offer, I guess I would need to fork the project, add the 
theme folder and make a PR right? I would appreciate some more help, 
actually, so I will try and do so.

**Comment by math-GH** [comment]
this tool could help to convert your LTR CSS to RTL CSS: https://rtlcss.com/playground/index.html (I haven't tried it much)

**Comment by Frenzie** [comment]
Just run `make rtl` once it's in there. I added it for a reason. ;-)

**Comment by math-GH** [comment]
> 

if you have Linux. If you have Windows, than you haven't.

**Comment by joelchrono12** [comment]
On January 15, 2022 4:11:51 PM UTC, maTh wrote:
>
>if you have Linux. If you have Windows, than you haven't.
>

I think its fair to say that most people self hosting stuff have Linux someway or another xD

**Comment by math-GH** [comment]
ok, here is not the right place for that "discussions" :D PHP is so simple, you do not need Linux ;)

**Comment by math-GH** [comment]
Done with #4400
