### ISSUE TITLE
[BUG] Could not initialize random number generator

### ISSUE THREAD

**Issue by FabioWidmer** [marienfressinaud/FreshRSS#4162]
**Describe the bug**
After switching the Docker tag from `1.18.1` to `1.19.0` and `1.19.1`, the following error appears and stops the container:
`(38)Function not implemented: AH00141: Could not initialize random number generator`

**To Reproduce**
Steps to reproduce the behaviour:
1. Install FreshRSS v1.18.1
2. Update FreshRSS to v1.19.1

**Expected behaviour**
Without changing anything the Docker container should start as usual after the update.

**Environment information**
- FreshRSS version: 1.19.1
- Installation type: Docker

**Comment by Frenzie** [comment]
I suspect the kernel of your outer environment is most likely to blame, not the container as such. Could you provide some information about it?

**Comment by Frenzie** [comment]
I found https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978045 which details the causes.

> This changed in libapr1 1.7, re-assigning to apr. I am not sure about 
the severity, though. According to the man page, getrandom has been 
introduced in linux 3.17. Debian 9 already has 4.9 so you have to have a 
kernel that is from Debian 8 to be affected by this.

**Comment by FabioWidmer** [comment]
Docker is running on a Synology server with the latest DSM installed. Kernel version is `3.10.108`.
Looks like the kernel is the problem but on a Synology server this cannot be changed.

**Comment by Frenzie** [comment]
Pinging @Alkarex

**Comment by Alkarex** [comment]
Which image are you using, more precisely?
We have a Debian and an Alpine version. Could you please try both?

* `freshrss/freshrss:1.19.1` (Debian)
* `freshrss/freshrss:1.19.1-alpine`

**Comment by FabioWidmer** [comment]
I was using the Debian one. After switching to the `1.19.1-alpine` tag it worked. Thanks!

**Comment by Alkarex** [comment]
Discussion for newer workarounds https://github.com/FreshRSS/FreshRSS/discussions/5987#discussioncomment-7956032
