### ISSUE TITLE
[BUG] Can't login - Header error : Deprecated: ctype_alnum()

### ISSUE THREAD

**Issue by ellypsis** [marienfressinaud/FreshRSS#4180]
**Describe the bug**
I can't login with my previously working account.

**To Reproduce**
1. System update on server (Archlinux)
2. Reload Freshrss page. Header showing with this 2 lines :
```
Deprecated: ctype_alnum(): Argument of type null will be interpreted as string in the future in /srv/http/freshrss.msquare.ovh/app/Models/FormAuth.php on line 18

Deprecated: ctype_alnum(): Argument of type null will be interpreted as string in the future in /srv/http/freshrss.msquare.ovh/app/Models/FormAuth.php on line 66
```
3. Try to log -> page refresh to login page, clearing credentials.

**Expected behavior**
Logging in as usual, and no header.

**Environment information (please complete the following information):**
- Device: Lenovo X1 Carbon 3rd Gen
- OS: Archlinux
- Browser: Firefox 96.0.2
- FreshRSS version: where to check if I can't log in?
- Database version: SQlite
- PHP version: 8.1.2
- Installation type: self hosted on Archlinux server

**Additional context**
I tried to update FreshRSS from a Zip Archive to the last version, with no luck. Same problem.
I tried to install a new FreshRSS instance from scratch, works fine.
Possible workaround : manual transfer of users ans its data to the newly installed instance (settings & database)

**Comment by Frenzie** [comment]
The version is pulled from constants.php

https://github.com/FreshRSS/FreshRSS/blob/24afafb74d422bd8d7526719046253279cb7e713/constants.php#L6

> Deprecated: ctype_alnum(): Argument of type null will be interpreted as string in the future in /srv/http/freshrss.msquare.ovh/app/Models/FormAuth.php on line 18

This just sounds like a meaningless warning? $token is a string.

**Comment by Alkarex** [comment]
@ellypsis Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/4182

**Comment by Frenzie** [comment]
Ah, it could sometimes be null instead of empty string. Kinda petty of the function to complain about that one all of a sudden tbh.
