### ISSUE TITLE
[BUG] error importing json with timestamps in epoch milliseconds (e.g. feedly)

### ISSUE THREAD

**Issue by otyu** [marienfressinaud/FreshRSS#4185]
**Describe the bug**
When importing a json with timestamps in epoch milliseconds (for example, starred items of Feedly), items are parsed with a blown up time.

**To Reproduce**
1. Take a json with epoch in milliseconds, e.g. which shows `"published": 1228138394000` (December 1, 2008)
2. Import in Freshrss.
3. Check the database table `user_entry` for the item and find a wrong timestamp (e.g. `2147483647` (i.e. January 19, 2038) for the above item)

**Expected behavior**
Convert to the proper timestamp. Check if in milliseconds (e.g. >= 1000000000) and if so, remove the three last digits.

**Environment information (please complete the following information):**
- FreshRSS version: 1.19.1
- Database version: mariadb 10.7
- PHP version: 7.4.25
- Installation type: docker

**Additional context**

I created a small python script to convert the json to be imported.

```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import json
input_file=open('input.json','r')
data=json.load(input_file)
input_file.close()

# cycle through items
for i in data['items']:
	#cycle through all keys
	for k in i.keys():
		#check if value is a timestamp in milliseconds
		if isinstance(i[k], int) and i[k] >=  1000000000 :
			#convert to seconds
			i[k]=int(i[k]/1000)

#write output
output_file = open('output.json','w')
json.dump(data, output_file)
output_file.close()
```

**Comment by Alkarex** [comment]
Could you please provide an example of such a JSON file?

**Comment by otyu** [comment]
Thank you for your answer.

This is a prettyprint of an item of my feedly export, substituting some texts for readability. 

```
{
    "id": "user/____/tag/global.saved",
    "items": [
        {
            "actionTimestamp": 1441858162237,
            "alternate": [
                {
                    "href": "http://...",
                    "type": "text/html"
                }
            ],
            "author": "AUTHOR",
            "content": {
                "content": "CONTENT",
                "direction": "ltr"
            },
            "crawled": 1441806678532,
            "fingerprint": "FINGERPRINT_STRING",
            "id": "ID_STRING",
            "keywords": [
                "KEYWORD_1"
            ],
            "origin": {
                "htmlUrl": "http://journals.aps.org/prd/",
                "streamId": "feed/http://feeds.aps.org/rss/recent/prd.xml",
                "title": "Recent Articles in Phys. Rev. D"
            },
            "originId": "http://link.aps.org/doi/...",
            "published": 1441720800000,
            "summary": {
                "content": "CONTENT",
                "direction": "ltr"
            },
            "tags": [
                {
                    "id": "user/____/tag/global.saved",
                    "label": "Saved For Later"
                },
                {
                    "id": "user/____/tag/global.read",
                    "label": ""
                }
            ],
            "title": "TITLE",
            "unread": false,
            "visual": {
                "url": "none"
            }
        }
    ]
}
```

**Comment by Alkarex** [comment]
@otyu Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/4186

**Comment by otyu** [comment]
@Alkarex  thank you for your timely commit.
I am terribly sorry to take so long to answer.
It seems this issue has been already closed, and the commit already verified. Nevertheless, I'd like to report that I tried the patch, and it seems to have worked fine for my json files.

As to how I tested, I went to the patch page, checked the "Files changed", clicked "View file", and downloaded the Raw file to my system. I then imported the file to my docker container, and changed `FreshRSS_ActionController` to `Minz_ActionController`. Importing a feedly json file went fine, resulting in sane timestamps. Straightforward, but took me a lot of time to understand how to "test a patch".

Once again, thank you for your swift resolution.

**Comment by Alkarex** [comment]
No worries @otyu . I went a bit fast because we are in a release candidate phase for FreshRSS 1.19.2 and I wanted to include this patch. Thanks for the feedback. What you did worked in this case. It is more robust to do those things via git though, for another time :-) Now you can also download our current edge branch (1.19.2-dev), which includes this patch. Tests welcome https://github.com/FreshRSS/FreshRSS/issues/4179
