### ISSUE TITLE
Minor regression in the Origine theme

### ISSUE THREAD

**Issue by Alkarex** [marienfressinaud/FreshRSS#4187]
![image](https://user-images.githubusercontent.com/1008324/151854308-5289be3c-d87e-4262-ade2-834dc9c814c7.png)

**Comment by Alkarex** [comment]
Maybe something for you @math-GH if you can

**Comment by math-GH** [comment]
fixed it, but it is not the 100% perfect solution for all this small issues. I have to clean up some HTML
