### ISSUE TITLE
[Feature] Subscribe to a dynamic OPML Feed

### ISSUE THREAD

**Issue by reidcooper** [marienfressinaud/FreshRSS#4191]
**Description**

I am currently an active user of Inoreader and an exciting feature that they provide is dynamic OPML Subscriptions.

Rather than importing an OPML feed, you would subscribe to it.

In their words:

> Importing an OPML
> If you import an OPML file in your RSS reader, you are creating a static copy of the reading list. If the owner of the original list updates the list, this change will not be shown in your feed collection. 

> Subscribing to an OPML
> An OPML subscription, however, creates a live connection between the original source and your feed folder. Whenever a feed is added or deleted from the original list, the change will be reflected in your subscriptions. The notification system in Inoreader will notify you that new feeds were imported or existing feeds were removed. 

I currently subscribe to the Engineering Blogs List OPML from this Github Repo (https://github.com/kilimchoi/engineering-blogs). The OPML feed that I subscribe to is here [engineering_blogs.opml](https://raw.githubusercontent.com/kilimchoi/engineering-blogs/master/engineering_blogs.opml)

Since this feed is dynamically updated with new feeds and deletion of stale feeds, the OPML is ever-changing. It's nice to see that those feed changes are reflected in my FreshRSS instance.

**Describe the solution you’d like**

Provide the ability to subscribe to an OPML feed such as: `https://raw.githubusercontent.com/kilimchoi/engineering-blogs/master/engineering_blogs.opml`.

Configuration options could be:

* URL
* Description of this OPML subscription
* Folder (all feeds are categorized in this folder)
* Synchronization Options (Append Only, Full-Sync)

**Comment by Alkarex** [comment]
Hello,
Adding new feeds automatically would be relatively easy to implement. Automatically removing feeds could be problematic though, as this would delete favourites, labels, etc. Especially problematic if the user was already subscribed to one of the feeds of the OPML.

**Comment by Alkarex** [comment]
What do you think of the value of automatically *adding* new feeds, but not removing feeds, @reidcooper ?

**Comment by reidcooper** [comment]
@Alkarex  Thank you for your response and I appreciate your development. I understand what you're saying - the current platform may not easily support auto deletion. 

If a user can auto subscribe to new feeds that get appendeD to the OPML file, I think that's a great compromise. 

Have you used dynamic OPML feeds before? Pretty neat to use crowd sourced feeds.

**Comment by Alkarex** [comment]
In the coming days, I plan to write a new feature, which will allow new types of sources (I won't say much before I have an actual PR to show), and which will make it easier to write what you ask. Keep an eye open, and fill free to link to this issue so that it is not forgotten (there are also many other things stacking up :-P)

**Comment by reidcooper** [comment]
@Alkarex Great! I will keep an eye out :) Thanks! No rush.

**Comment by Alkarex** [comment]
This is the PR I was hinting, introducing the ability to consume different types of sources https://github.com/FreshRSS/FreshRSS/pull/4220

**Comment by reidcooper** [comment]
@Alkarex , thanks for responding! I read over the PR and I can see the power that this functionality will bring. I wasn't able to see how this could address my feature request. 

https://raw.githubusercontent.com/kilimchoi/engineering-blogs/master/engineering_blogs.opml

This OPML file is dynamically generated with new RSS feeds. A list of feeds. 

Would your PR (or future) be able to see those RSS feeds from the OPML and then subscribe to those feeds?

**Comment by Alkarex** [comment]
The PR I refer to is just the first to enable the support of different types of sources. Something that is also needed for what you are asking

**Comment by Alkarex** [comment]
I will try to make it happen https://github.com/FreshRSS/FreshRSS/pull/4407 . Also, I would like at the same time FreshRSS to be a **source** of Dynamic OPML, and the main part of that feature is already implemented in the draft PR, but details such as better security tokens must be added.

Background reading:
* http://web.archive.org/web/20060101040915/http://www.reallysimplesyndication.com/2005/10/13
* https://techcrunch.com/2005/10/16/my-thoughts-on-reading-lists/
* http://scripting.com/2017/06/26.html#a080636

The easy part is to add new categories and feeds. The more difficult part is to find out what to do with feeds moved, categories renamed, feeds with a URL that has changed / been (permanently) redirected, feeds deleted, feeds referenced in more than one dynamic OPML, etc.

**Comment by bursaar** [comment]
Being able to subscribe to a dynamic OPML is awesome – I'm setting up a household instance of FreshRSS and I'd love for everyone in the family to have the ability to add and remove feeds from a shared category; I feel a dynamic OPML is a nice way to achieve that. For now, we're making do with sharing RSS feeds from a special "Shared With Family" category each of us has in their account, and from a special "Share with Family" label we also each have, but this clobbers the source of the articles and makes the subscribed category kind of hard to read for subscribers, when you have ten or twenty posts dropping into their feed, but all from "Dad's Shared Feeds".

**Comment by Alkarex** [comment]
@bursaar Please open a new discussion for your use-case, and let's see whether we could find an approach

**Comment by marauder37** [comment]
> Being able to subscribe to a dynamic OPML is awesome

For me, that's what I wanted to say. Thank you for all your work @Alkarex
